{
 "title": "Kubernetes: CronJob",
 "description": "Kubernetes: CronJob Description",
 "tags": [
  "kubernetes",
  "cronjob"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(kube_cronjob_info, cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_cronjob_info{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "cronjob",
    "label": "CronJob",
    "query": "label_values(kube_cronjob_info{cluster=\"$cluster\",namespace=\"$namespace\"}, cronjob)"
   }
  ]
 },
 "panels": [
  {
   "title": "SCHEDULE",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_cronjob_info{cluster=\"$cluster\",namespace=\"$namespace\",cronjob=\"$cronjob\"}",
     "legendFormat": "{{ schedule }}"
    }
   ]
  },
  {
   "title": "SUSPEND",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_cronjob_spec_suspend{cluster=\"$cluster\",namespace=\"$namespace\",cronjob=\"$cronjob\"}"
    }
   ]
  },
  {
   "title": "ACTIVE",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_cronjob_status_active{cluster=\"$cluster\",namespace=\"$namespace\",cronjob=\"$cronjob\"}"
    }
   ]
  },
  {
   "title": "LAST SCHEDULE",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_cronjob_status_last_schedule_time{cluster=\"$cluster\",namespace=\"$namespace\",cronjob=\"$cronjob\"}*1000"
    }
   ]
  },
  {
   "title": "NEXT SCHEDULE",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_cronjob_next_schedule_time{cluster=\"$cluster\",namespace=\"$namespace\",cronjob=\"$cronjob\"}*1000"
    }
   ]
  },
  {
   "title": "AGE",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - kube_cronjob_created{cluster=\"$cluster\",namespace=\"$namespace\",cronjob=\"$cronjob\"}"
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "kube_job_owner{cluster=\"$cluster\",namespace=\"$namespace\",owner_kind=\"CronJob\",owner_name=\"$cronjob\"}",
     "legendFormat": "{{ job_name }}"
    }
   ]
  }
 ]
}