{
 "title": "Kubernetes: Workloads",
 "description": "Kubernetes: Workloads Overview",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(kube_pod_info,cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info{cluster=~\"$cluster\"}, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Deployments",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{cluster=~\"$cluster\",namespace=~\"$namespace\"})",
     "legendFormat": "Available"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{cluster=~\"$cluster\",namespace=~\"$namespace\"})",
     "legendFormat": "Unavailable"
    }
   ]
  },
  {
   "title": "ReplicaSets",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_replicaset_status_ready_replicas{cluster=~\"$cluster\",namespace=~\"$namespace\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(kube_replicaset_status_replicas-kube_replicaset_status_ready_replicas{cluster=~\"$cluster\",namespace=~\"$namespace\"})",
     "legendFormat": "NotReady"
    }
   ]
  },
  {
   "title": "StatefulSets",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_statefulset_status_replicas_ready{cluster=~\"$cluster\",namespace=~\"$namespace\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(kube_statefulset_status_replicas-kube_statefulset_status_replicas_ready{cluster=~\"$cluster\",namespace=~\"$namespace\"})",
     "legendFormat": "NotReady"
    }
   ]
  },
  {
   "title": "DaemonSets",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_daemonset_status_number_available{cluster=~\"$cluster\",namespace=~\"$namespace\"})",
     "legendFormat": "Available"
    },
    {
     "expr": "sum(kube_daemonset_status_number_unavailable{cluster=~\"$cluster\",namespace=~\"$namespace\"})",
     "legendFormat": "Unavailable"
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_job_status_succeeded{cluster=~\"$cluster\",namespace=~\"$namespace\"})",
     "legendFormat": "Succeeded"
    },
    {
     "expr": "sum(kube_job_status_active{cluster=~\"$cluster\",namespace=~\"$namespace\"})",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(kube_job_status_failed{cluster=~\"$cluster\",namespace=~\"$namespace\"})",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "CronJobs",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_cronjob_info{cluster=~\"$cluster\",namespace=~\"$namespace\"})-sum(kube_cronjob_spec_suspend{cluster=~\"$cluster\",namespace=~\"$namespace\"})",
     "legendFormat": "Scheduled"
    },
    {
     "expr": "sum(kube_cronjob_spec_suspend{cluster=~\"$cluster\",namespace=~\"$namespace\"})",
     "legendFormat": "Suspend"
    }
   ]
  },
  { "title": "Workloads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Deployments",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "kube_deployment_created{cluster=~\"$cluster\",namespace=~\"$namespace\"}*1000"
    }
   ]
  },
  {
   "title": "ReplicaSets",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "kube_replicaset_created{cluster=~\"$cluster\",namespace=~\"$namespace\"}*1000"
    }
   ]
  },
  {
   "title": "StatefulSets",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "kube_statefulset_created{cluster=~\"$cluster\",namespace=~\"$namespace\"}*1000"
    }
   ]
  },
  {
   "title": "DaemonSets",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "kube_daemonset_created{cluster=~\"$cluster\",namespace=~\"$namespace\"}*1000"
    }
   ]
  },
  {
   "title": "CronJobs",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "kube_cronjob_created{cluster=~\"$cluster\",namespace=~\"$namespace\"}*1000"
    },
    {
     "expr": "kube_cronjob_next_schedule_time{cluster=~\"$cluster\",namespace=~\"$namespace\"}*1000"
    },
    {
     "expr": "kube_cronjob_info{cluster=~\"$cluster\",namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "kube_job_created{cluster=~\"$cluster\",namespace=~\"$namespace\"}*1000"
    }
   ]
  },
  { "title": "Resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } }
 ]
}