{
 "title": "Kubernetes: DaemonSet",
 "description": "Kubernetes: DaemonSet Description",
 "tags": [
  "kubernetes",
  "daemonset"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(kube_daemonset_metadata_generation, cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_daemonset_metadata_generation{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "daemonset",
    "label": "DaemonSet",
    "query": "label_values(kube_daemonset_metadata_generation{cluster=\"$cluster\",namespace=\"$namespace\"}, daemonset)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\",namespace=\"$namespace\",created_by_kind=\"DaemonSet\",created_by_name=\"$daemonset\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",container!=\"\"}[1m]))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",container!=\"\",container!=\"POD\"}[1m]))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",container!=\"\",container!=\"POD\"})",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",container!=\"\",container!=\"POD\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "DESIRED",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_daemonset_status_desired_number_scheduled{cluster=\"$cluster\",namespace=\"$namespace\",daemonset=\"$daemonset\"}"
    }
   ]
  },
  {
   "title": "CURRENT",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_daemonset_status_current_number_scheduled{cluster=\"$cluster\",namespace=\"$namespace\",daemonset=\"$daemonset\"}"
    }
   ]
  },
  {
   "title": "READY",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_daemonset_status_number_ready{cluster=\"$cluster\",namespace=\"$namespace\",daemonset=\"$daemonset\"}"
    }
   ]
  },
  {
   "title": "UPDATED",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_daemonset_updated_number_scheduled{cluster=\"$cluster\",namespace=\"$namespace\",daemonset=\"$daemonset\"}"
    }
   ]
  },
  {
   "title": "AVAILABLE",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_daemonset_status_number_available{cluster=\"$cluster\",namespace=\"$namespace\",daemonset=\"$daemonset\"}"
    }
   ]
  },
  {
   "title": "AGE",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - kube_daemonset_created{cluster=\"$cluster\",namespace=\"$namespace\",daemonset=\"$daemonset\"}"
    }
   ]
  },
  {
   "title": "Replicas Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kube_daemonset_status_number_ready{cluster=\"$cluster\",namespace=\"$namespace\",daemonset=\"$daemonset\"}",
     "legendFormat": "Ready"
    },
    {
     "expr": "kube_daemonset_status_number_available{cluster=\"$cluster\",namespace=\"$namespace\",daemonset=\"$daemonset\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "kube_daemonset_status_number_unavailable{cluster=\"$cluster\",namespace=\"$namespace\",daemonset=\"$daemonset\"}",
     "legendFormat": "Unavailable"
    },
    {
     "expr": "kube_daemonset_status_number_misscheduled{cluster=\"$cluster\",namespace=\"$namespace\",daemonset=\"$daemonset\"}",
     "legendFormat": "Misscheduled"
    },
    {
     "expr": "kube_daemonset_updated_number_scheduled{cluster=\"$cluster\",namespace=\"$namespace\",daemonset=\"$daemonset\"}",
     "legendFormat": "Updated"
    }
   ]
  },
  { "title": "Disk and Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Total Filesystem Reads/Writes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",container!=\"\",container!=\"POD\"}[1m]))",
     "legendFormat": "Reads"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",container!=\"\",container!=\"POD\"}[1m]))",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Filesystem Read/Write",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod,device) (rate(container_fs_reads_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}[1m]))",
     "legendFormat": "Reads: {{ pod }}, {{ device }}"
    },
    {
     "expr": "sum by (pod,device) (rate(container_fs_writes_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}[1m]))",
     "legendFormat": "Writes: {{ pod }}, {{ device }}"
    }
   ]
  },
  {
   "title": "Total Network",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}[1m]))",
     "legendFormat": "Transmit"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}[1m]))",
     "legendFormat": "Receive"
    }
   ]
  },
  {
   "title": "Network TX/RX",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod,interface) (rate(container_network_transmit_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}[1m]))",
     "legendFormat": "TX: {{ pod }}, {{ interface }}"
    },
    {
     "expr": "sum by (pod,interface)(rate(container_network_receive_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}[1m]))",
     "legendFormat": "RX: {{ pod }}, {{ interface }}"
    }
   ]
  },
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Pod Info",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "kube_pod_info{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  }
 ]
}