{
 "title": "Kubernetes: Pod Overview",
 "tags": [
  "kubernetes",
  "pod"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(kube_pod_info,cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info{cluster=~\"$cluster\"}, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{cluster=~\"$cluster\",namespace=~\"$namespace\"}, pod)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(kube_pod_container_info{cluster=~\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\"}, container)"
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Not running pod",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (cluster,namespace,pod,phase) (kube_pod_status_phase{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",phase!=\"Running\"} == 1)"
    }
   ]
  },
  {
   "title": "Abnormally waiting container during last selected range",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (cluster,namespace,pod,container,reason) (sum_over_time(kube_pod_container_status_waiting_reason{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\",reason!~\"ContainerCreating\"}[$__range]) > 0)"
    }
   ]
  },
  {
   "title": "Abnormally terminated container during last selected range",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (cluster,namespace,pod,container,reason) (sum_over_time(kube_pod_container_status_terminated_reason{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\",reason!~\"Completed\"}[$__range]) > 0)"
    }
   ]
  },
  {
   "title": "Last abnormally terminated container",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (cluster,namespace,pod,container,reason) (kube_pod_container_status_last_terminated_reason{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\",reason!~\"Completed\"} == 1)"
    }
   ]
  },
  { "title": "Resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "CPU Usage",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (cluster,namespace,pod,container) (rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\",container!=\"POD\",container!=\"\"}[1m])) * 1000"
    },
    {
     "expr": "sum by (cluster,namespace,pod,container) (kube_pod_container_resource_limits_cpu_cores{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\",container!=\"POD\",container!=\"\"}) * 1000"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (cluster,namespace,pod,container) (container_memory_working_set_bytes{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\",container!=\"POD\",container!=\"\"})"
    },
    {
     "expr": "sum by (cluster,namespace,pod,container) (kube_pod_container_resource_limits_memory_bytes{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\",container!=\"POD\",container!=\"\"})"
    }
   ]
  },
  {
   "title": "Volume Usage",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (cluster,namespace,pod,persistentvolumeclaim) (kubelet_volume_stats_used_bytes{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"})"
    },
    {
     "expr": "sum by (cluster,namespace,pod,persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"})"
    }
   ]
  }
 ]
}