{
 "title": "Kubernetes: Deployment Overview",
 "description": "Kubernetes: Deployment Overview",
 "tags": [
  "kubernetes",
  "deployment"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(kube_deployment_metadata_generation, cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_deployment_metadata_generation{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": "label_values(kube_deployment_metadata_generation{cluster=\"$cluster\",namespace=\"$namespace\"}, deployment)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\",namespace=\"$namespace\",created_by_kind=\"ReplicaSet\",created_by_name=~\"$deployment-[-a-z0-9]{7,10}\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Deployment Create Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - kube_deployment_created{cluster=\"$cluster\",namespace=\"$namespace\",deployment=\"$deployment\"}"
    }
   ]
  },
  {
   "title": "DESIRED",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{cluster=\"$cluster\",namespace=\"$namespace\",deployment=\"$deployment\"}"
    }
   ]
  },
  {
   "title": "AVAILABLE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{cluster=\"$cluster\",namespace=\"$namespace\",deployment=\"$deployment\"}"
    }
   ]
  },
  {
   "title": "Observed Generation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_observed_generation{cluster=\"$cluster\",deployment=\"$deployment\",namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Metadata Generation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_metadata_generation{cluster=\"$cluster\",deployment=\"$deployment\",namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Total CPU",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",container!=\"\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",container!=\"\"}) "
    }
   ]
  },
  {
   "title": "Total Filesystem Reads/Writes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",container!=\"\"}[1m])) + sum(rate(container_fs_writes_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",container!=\"\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total Network",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}[1m])) + sum(rate(container_network_receive_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}[1m]))"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",container!=\"\"}[1m]))"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",container!=\"\"})",
     "legendFormat": "Current : {{ pod }} "
    }
   ]
  },
  {
   "title": "Filesystem Read/Write",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_fs_reads_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",container!=\"\"}[1m]))",
     "legendFormat": "Reads: {{ pod }}"
    },
    {
     "expr": "sum by (pod) (rate(container_fs_writes_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",container!=\"\"}[1m]))",
     "legendFormat": "Writes: {{ pod }}"
    }
   ]
  },
  {
   "title": "Network TX/RX",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_network_transmit_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}[1m]))",
     "legendFormat": "TX: {{ pod }}"
    },
    {
     "expr": "sum by (pod)(rate(container_network_receive_bytes_total{cluster=\"$cluster\",namespace=\"$daemonset_namespace\",pod=~\"$pod\"}[1m]))",
     "legendFormat": "RX: {{ pod }}"
    }
   ]
  },
  {
   "title": "Replica Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(kube_deployment_status_replicas_available{cluster=\"$cluster\",namespace=~\"$namespace\",deployment=~\"$deployment\"}) by(namespace, deployment)",
     "legendFormat": "Available"
    },
    {
     "expr": "avg(kube_deployment_status_replicas_unavailable{cluster=\"$cluster\",namespace=~\"$namespace\",deployment=~\"$deployment\"}) by(namespace, deployment)",
     "legendFormat": "Unavailable"
    },
    {
     "expr": "avg(kube_deployment_status_replicas_updated{cluster=\"$cluster\",namespace=~\"$namespace\",deployment=~\"$deployment\"}) by(namespace, deployment)",
     "legendFormat": "Updated"
    }
   ]
  },
  {
   "title": "Spec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(kube_deployment_spec_replicas{cluster=\"$cluster\",namespace=~\"$namespace\",deployment=~\"$deployment\"}) by(namespace, deployment)",
     "legendFormat": "Replicas"
    },
    {
     "expr": "avg(kube_deployment_spec_paused{cluster=\"$cluster\",namespace=~\"$namespace\",deployment=~\"$deployment\"}) by(namespace, deployment)",
     "legendFormat": "Paused"
    }
   ]
  }
 ]
}