{
 "title": "Kubernetes: Namespace Overview",
 "tags": [
  "kubernetes",
  "namespace"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(kube_node_info,cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
   }
  ]
 },
 "panels": [
  { "title": "POD Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Created",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - kube_namespace_created{cluster=\"$cluster\",namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "POD Count (Namespace)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{cluster=\"$cluster\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "POD Count (Namespace)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{cluster=\"$cluster\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Pod Restart",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts{cluster=\"$cluster\",namespace=~\"$namespace\"} or kube_pod_container_status_restarts_total{cluster=\"$cluster\",namespace=~\"$namespace\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg(kube_pod_status_phase{cluster=\"$cluster\",namespace=~\"$namespace\"}) by(namespace, pod, phase)) by(phase)",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  { "title": "POD Resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",namespace=\"$namespace\",container_name!=\"POD\",container_name!=\"\"}[2m])) "
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",namespace=\"$namespace\",container_name!=\"\",container_name!=\"POD\"}[1m]))",
     "legendFormat": "Current: {{ pod }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\",namespace=\"$namespace\",container_name!=\"POD\",container_name!=\"\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by(pod) (container_memory_working_set_bytes{cluster=\"$cluster\",namespace=\"$namespace\",container!=\"POD\",container!=\"\"})",
     "legendFormat": "Current: {{ pod }}"
    }
   ]
  },
  {
   "title": "Volume",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_used_bytes and on (persistentvolumeclaim) kube_pod_spec_volumes_persistentvolumeclaims_info{cluster=\"$cluster\",namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Volume Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kubelet_volume_stats_capacity_bytes and on (persistentvolumeclaim) kube_pod_spec_volumes_persistentvolumeclaims_info{cluster=\"$cluster\",namespace=\"$namespace\"}",
     "legendFormat": "Capacity : {{ persistentvolumeclaim }}"
    },
    {
     "expr": "kubelet_volume_stats_used_bytes and on (persistentvolumeclaim) kube_pod_spec_volumes_persistentvolumeclaims_info{cluster=\"$cluster\",namespace=\"$namespace\"}",
     "legendFormat": "Used : {{ persistentvolumeclaim }}"
    }
   ]
  },
  {
   "title": "Filesystem Read/Write",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\",container_name!=\"POD\",container_name!=\"\"}[1m])) + sum(rate(container_fs_writes_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\",container_name!=\"POD\",container_name!=\"\"}[1m]))"
    }
   ]
  },
  {
   "title": "Filesystem Read/Write",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 29 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_fs_reads_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\",container!=\"POD\",container!=\"\"}[2m]))",
     "legendFormat": "Reads : {{ pod }}"
    },
    {
     "expr": "sum by (pod) (rate(container_fs_writes_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\",container!=\"POD\",container!=\"\"}[2m]))",
     "legendFormat": "Writes : {{ pod }}"
    }
   ]
  },
  {
   "title": "Network RX/TX",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\"}[1m])) + sum(rate(container_network_receive_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\"}[1m])) "
    }
   ]
  },
  {
   "title": "Network TX/RX",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 34 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\",interface=\"eth0\"}[2m])",
     "legendFormat": "TX : {{ pod }}"
    },
    {
     "expr": "rate(container_network_receive_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\",interface=\"eth0\"}[2m])",
     "legendFormat": "RX : {{ pod }}"
    }
   ]
  }
 ]
}