{
 "title": "Kubernetes: Pod",
 "tags": [
  "kubernetes",
  "pods"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(kube_pod_info,cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\",namespace=\"$namespace\"}, pod)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(kube_pod_container_info{cluster=\"$cluster\",namespace=\"$namespace\", pod=\"$pod\"}, container)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=\"$pod\",container=~\"$container\",container!=\"POD\",container!=\"\"}[1m]))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container) (rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=\"$pod\",container=~\"$container\",container!=\"\",container!=\"POD\"}[1m]))",
     "legendFormat": "Current: {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_requests_cpu_cores{cluster=\"$cluster\",namespace=\"$namespace\",pod=\"$pod\",container=~\"$container\",container!=\"POD\"}",
     "legendFormat": "Request: {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{cluster=\"$cluster\",namespace=\"$namespace\",pod=\"$pod\",container=~\"$container\",container!=\"POD\"}",
     "legendFormat": "Limit: {{ container }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\",namespace=\"$namespace\",pod=\"$pod\",container!=\"POD\",container=\"\"})",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by(container) (container_memory_working_set_bytes{cluster=\"$cluster\",namespace=\"$namespace\",pod=\"$pod\",container=~\"$container\",container!=\"POD\",container!=\"\"})",
     "legendFormat": "Current: {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_requests_memory_bytes{cluster=\"cluster\",namespace=\"$namespace\",pod=\"$pod\",container=~\"$container\"}",
     "legendFormat": "Request: {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{cluster=\"cluster\",namespace=\"$namespace\",pod=\"$pod\",container=~\"$container\"}",
     "legendFormat": "Limit: {{ container }}"
    }
   ]
  },
  {
   "title": "STATUS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_status_phase{cluster=\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"} == 1",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_status_phase{cluster=\"$cluster\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "READY",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (kube_pod_container_status_ready{cluster=\"$cluster\",namespace=\"$namespace\",pod=\"$pod\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "count by (pod) (kube_pod_container_info{cluster=\"$cluster\",namespace=\"$namespace\",pod=\"$pod\"})",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Ready",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{cluster=\"$cluster\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "RESTARTS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (kube_pod_container_status_restarts_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=\"$pod\",container=~\"$container\"})"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "AGE",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - kube_pod_created{cluster=\"$cluster\",namespace=\"$namespace\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_start_time{cluster=\"$cluster\",namespace=\"$namespace\",pod=\"$pod\"}*1000"
    }
   ]
  },
  {
   "title": "Kind",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_info{cluster=\"$cluster\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "{{created_by_kind}}"
    }
   ]
  },
  {
   "title": "Waiting Reason",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_waiting_reason{cluster=\"$cluster\",namespace=\"$namespace\",pod=\"$pod\",container=~\"$container\"}",
     "legendFormat": "{{reason}}@{{container}}"
    }
   ]
  },
  {
   "title": "Terminated Reason",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_terminated_reason{cluster=\"$cluster\",namespace=\"$namespace\",pod=\"$pod\",container=~\"$container\"}",
     "legendFormat": "{{reason}}@{{container}}"
    }
   ]
  },
  {
   "title": "Last Terminated Reason",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{cluster=\"$cluster\",namespace=\"$namespace\",pod=\"$pod\",container=~\"$container\"}",
     "legendFormat": "{{reason}}@{{container}}"
    }
   ]
  },
  { "title": "Disk and Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Volume",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_used_bytes and on (persistentvolumeclaim) kube_pod_spec_volumes_persistentvolumeclaims_info{cluster=\"$cluster\",pod=\"$pod\"})"
    }
   ]
  },
  {
   "title": "Volume Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kubelet_volume_stats_capacity_bytes and on (persistentvolumeclaim) kube_pod_spec_volumes_persistentvolumeclaims_info{cluster=\"$cluster\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "Capacity : {{ persistentvolumeclaim }}"
    },
    {
     "expr": "kubelet_volume_stats_used_bytes and on (persistentvolumeclaim) kube_pod_spec_volumes_persistentvolumeclaims_info{cluster=\"$cluster\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "Used : {{ persistentvolumeclaim }}"
    }
   ]
  },
  {
   "title": "Network RX/TX",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=\"$pod\"}[1m]))",
     "legendFormat": "Transmit"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=\"$pod\"}[1m])) ",
     "legendFormat": "Receive"
    }
   ]
  },
  {
   "title": "Network TX/RX",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=\"$pod\",interface=\"eth0\"}[1m])",
     "legendFormat": "TX : {{ pod }}"
    },
    {
     "expr": "rate(container_network_receive_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=\"$pod\",interface=\"eth0\"}[1m])",
     "legendFormat": "RX : {{ pod }}"
    }
   ]
  },
  {
   "title": "Filesystem Read/Write",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",container!=\"POD\",container!=\"\"}[1m]))",
     "legendFormat": "Reads"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",container!=\"POD\",container!=\"\"}[1m]))",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Filesystem Read/Write",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (container,device) (rate(container_fs_reads_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=\"$pod\",container=~\"$container\",container!=\"POD\",container!=\"\"}[1m]))",
     "legendFormat": "Reads : {{ container }} {{ device }}"
    },
    {
     "expr": "sum by (container,device) (rate(container_fs_writes_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=\"$pod\",container=~\"$container\",container!=\"POD\",container!=\"\"}[1m]))",
     "legendFormat": "Writes : {{ container }} {{ device }}"
    }
   ]
  },
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Pod Info",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "kube_pod_info{cluster=\"$cluster\",namespace=\"$namespace\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Container Info",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "kube_pod_container_info{cluster=\"$cluster\",namespace=\"$namespace\",pod=\"$pod\",container=~\"$container\"}"
    }
   ]
  }
 ]
}