{
 "title": "Kubernetes: Deployment",
 "description": "Kubernetes: Deployment Description",
 "tags": [
  "kubernetes",
  "deployment"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(kube_deployment_metadata_generation, cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_deployment_metadata_generation{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": "label_values(kube_deployment_metadata_generation{cluster=\"$cluster\",namespace=\"$namespace\"}, deployment)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\",namespace=\"$namespace\",created_by_kind=\"ReplicaSet\",created_by_name=~\"$deployment-[-a-z0-9]{7,10}\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",container!=\"\",container!=\"POD\"}[1m]))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",container!=\"\"}[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",container!=\"\"}) ",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",container!=\"\",container!=\"POD\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "AGE",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - kube_deployment_created{cluster=\"$cluster\",namespace=\"$namespace\",deployment=\"$deployment\"}"
    }
   ]
  },
  {
   "title": "DESIRED",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{cluster=\"$cluster\",namespace=\"$namespace\",deployment=\"$deployment\"}"
    }
   ]
  },
  {
   "title": "UPDATED",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_updated{cluster=\"$cluster\",namespace=\"$namespace\",deployment=\"$deployment\"}"
    }
   ]
  },
  {
   "title": "AVAILABLE",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{cluster=\"$cluster\",namespace=\"$namespace\",deployment=\"$deployment\"}"
    }
   ]
  },
  {
   "title": "Metadata Generation",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_metadata_generation{cluster=\"$cluster\",deployment=\"$deployment\",namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Observed Generation",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_observed_generation{cluster=\"$cluster\",deployment=\"$deployment\",namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Spec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{cluster=\"$cluster\",namespace=\"$namespace\",deployment=\"$deployment\"}",
     "legendFormat": "Replicas"
    },
    {
     "expr": "kube_deployment_spec_paused{cluster=\"$cluster\",namespace=\"$namespace\",deployment=\"$deployment\"}",
     "legendFormat": "Paused"
    }
   ]
  },
  {
   "title": "Replicas Status",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_updated{cluster=\"$cluster\",namespace=\"$namespace\",deployment=\"$deployment\"}",
     "legendFormat": "Updated"
    },
    {
     "expr": "kube_deployment_status_replicas{cluster=\"$cluster\",namespace=\"$namespace\",deployment=\"$deployment\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "kube_deployment_status_replicas_available{cluster=\"$cluster\",namespace=\"$namespace\",deployment=\"$deployment\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "kube_deployment_status_replicas_unavailable{cluster=\"$cluster\",namespace=\"$namespace\",deployment=\"$deployment\"}",
     "legendFormat": "Unavailable"
    }
   ]
  },
  { "title": "Disk and Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Total Filesystem Reads/Writes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",container!=\"\"}[1m]))",
     "legendFormat": "Reads"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",container!=\"\"}[1m]))",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Filesystem Reads/Writes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_fs_reads_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",container!=\"\",container!=\"POD\"}[1m]))",
     "legendFormat": "Reads: {{ pod }}"
    },
    {
     "expr": "sum by (pod) (rate(container_fs_writes_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",container!=\"\",container!=\"POD\"}[1m]))",
     "legendFormat": "Writes: {{ pod }}"
    }
   ]
  },
  {
   "title": "Total Network",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}[1m]))",
     "legendFormat": "Transmit"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}[1m]))",
     "legendFormat": "Receive"
    }
   ]
  },
  {
   "title": "Network TX/RX",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (pod,interface) (rate(container_network_transmit_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}[1m]))",
     "legendFormat": "TX: {{ pod }}, {{ interface }}"
    },
    {
     "expr": "sum by (pod,interface) (rate(container_network_receive_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}[1m]))",
     "legendFormat": "RX: {{ pod }}, {{ interface }}"
    }
   ]
  },
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Pod Info",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "kube_pod_info{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Status Condition",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "kube_deployment_status_condition{cluster=\"$cluster\",namespace=\"$namespace\",deployment=\"$deployment\"} == 1"
    }
   ]
  },
  {
   "title": "Events",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "kubernetes_events{cluster=\"$cluster\",event_kind=\"Deployment\",event_namespace=\"$namespace\",event_name=\"$deployment\"}"
    }
   ]
  },
  {
   "title": "Pod Events",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "kubernetes_events{cluster=\"$cluster\",event_kind=\"Pod\",event_namespace=\"$namespace\",event_name=~\"$pod\"}"
    }
   ]
  }
 ]
}