apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: zcp-system
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: prometheus 
        component: node-exporter
      name: node-exporter
    spec:
      tolerations:
      - operator: Exists
      containers:
      - image: registry.au-syd.bluemix.net/cloudzcp/node-exporter:v0.15.2
        name: node-exporter
        args:
          - --path.procfs=/host/proc
          - --path.sysfs=/host/sys
          - --web.listen-address=0.0.0.0:9100
        ports:
        - containerPort: 9100
          hostPort: 9100
          name: metrics
        volumeMounts:
        - name: proc
          mountPath: /host/proc
          readOnly: true
        - name: sys
          mountPath: /host/sys
          readOnly: true
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
      hostNetwork: true
      hostPID: true
