{
 "title": "ZCP Services Status",
 "tags": [ "zcp-system" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(probe_http_status_code{namespace=\"zcp-system\"}, namespace)"
   },
   {
    "name": "site",
    "label": "site",
    "query": "label_values(probe_http_status_code{namespace=~\"$namespace\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "zcp-system", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Duration: $site",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{namespace=\"zcp-system\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Status: $site",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 8 },
   "repeat": "site",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=~\"$site\"}"
    }
   ]
  },
  {
   "title": "Status Code",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 8 },
   "repeat": "site",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_status_code{instance=~\"$site\"}"
    }
   ]
  }
 ]
}