{
 "title": "Kubernetes: Cluster Overview",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "node",
    "query": "label_values(kube_node_labels, node)"
   }
  ]
 },
 "panels": [
  { "title": "Resource Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Alerts Firing",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\",alertname!=\"DeadMansSwitch\"})"
    }
   ]
  },
  {
   "title": "Node Not Ready",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status!=\"true\"})"
    }
   ]
  },
  {
   "title": "Nodes Unschedulable",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable)"
    }
   ]
  },
  {
   "title": "Node Memory Pressure",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"MemoryPressure\",status=\"true\"})"
    }
   ]
  },
  {
   "title": "Node Disk Pressure",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"DiskPressure\",status=\"true\"})"
    }
   ]
  },
  {
   "title": "Running Pod",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(kubelet_running_pod_count)" }
   ]
  },
  {
   "title": "Running Container",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kubelet_running_container_count)"
    }
   ]
  },
  {
   "title": "Node: $node",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 6 },
   "repeat": "node",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kubelet_running_pod_count{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Node: $node",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 6 },
   "repeat": "node",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kubelet_running_container_count{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Node Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Node",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 35 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(node_uname_info{job=\"kubernetes-nodes-exporter\"})"
      }
     ]
    },
    {
     "title": "Total CPU",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 35 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(node_cpu{mode=\"user\",component=\"node-exporter\"})"
      }
     ]
    },
    {
     "title": "Used Memery",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 35 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal{job=\"kubernetes-nodes-exporter\"} - node_memory_MemFree - node_memory_Buffers - node_memory_Cached)"
      }
     ]
    },
    {
     "title": "Total Memery",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 35 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal{job=\"kubernetes-nodes-exporter\"})"
      }
     ]
    },
    {
     "title": "DIsk Usage(Local)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 35 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(node_filesystem_size{job=\"kubernetes-nodes-exporter\",mountpoint=\"/\"}) - sum(node_filesystem_avail{job=\"kubernetes-nodes-exporter\",mountpoint=\"/\"})"
      }
     ]
    },
    {
     "title": "DIsk Total(Local)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 35 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(node_filesystem_size{job=\"kubernetes-nodes-exporter\",mountpoint=\"/\"})"
      }
     ]
    },
    {
     "title": "Avg CPU Usage",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(100 - (avg by (cpu) (rate(node_cpu{job=\"kubernetes-nodes-exporter\",mode=\"idle\"}[5m])) * 100))"
      }
     ]
    },
    {
     "title": "Avg Memory Usage",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 38 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal{job=\"kubernetes-nodes-exporter\"} - node_memory_MemFree - node_memory_Buffers - node_memory_Cached ) / sum(node_memory_MemTotal{job=\"kubernetes-nodes-exporter\"}) * 100"
      }
     ]
    },
    {
     "title": "Avg Disk Usage(Local)",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 38 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "((sum(node_filesystem_size{job=\"kubernetes-nodes-exporter\",mountpoint=\"/\"}) - sum(node_filesystem_avail{job=\"kubernetes-nodes-exporter\",mountpoint=\"/\"})) / sum(node_filesystem_size{job=\"kubernetes-nodes-exporter\",mountpoint=\"/\"})) * 100"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 - (avg by (instance) (rate(node_cpu{job=\"kubernetes-nodes-exporter\",mode=\"idle\"}[5m])) * 100)",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 45 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "((node_memory_MemTotal{job=\"kubernetes-nodes-exporter\"} - node_memory_MemFree - node_memory_Buffers - node_memory_Cached) / node_memory_MemTotal{job=\"kubernetes-nodes-exporter\"}) * 100",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Disk Usage(Local)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "((node_filesystem_size{job=\"kubernetes-nodes-exporter\",mountpoint=\"/\"} - node_filesystem_avail{job=\"kubernetes-nodes-exporter\",mountpoint=\"/\"}) / node_filesystem_size{job=\"kubernetes-nodes-exporter\",mountpoint=\"/\"}) * 100",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Network Usage(RX/TX)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 45 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "(sum by (instance) (rate(node_network_receive_bytes{job=\"kubernetes-nodes-exporter\",device=~\"eth0|eth1\"}[5m])))",
       "legendFormat": "Inbound: {{ instance }} "
      },
      {
       "expr": "(sum by (instance) (rate(node_network_transmit_bytes{job=\"kubernetes-nodes-exporter\",device=~\"eth0|eth1\"}[5m])))",
       "legendFormat": "Outbound: {{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster CPU usage",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 53 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{id=\"/\"}[5m])) / sum(kube_node_status_capacity_cpu_cores) * 100"
      }
     ]
    },
    {
     "title": "Cluster Memory usage",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 53 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{id=\"/\"}) / sum(kube_node_status_capacity_memory_bytes) * 100"
      }
     ]
    },
    {
     "title": "Cluster Disk usage(Local)",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 53 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(container_fs_usage_bytes{id=\"/\",device=\"/dev/mapper/docker_data\"}) / sum(container_fs_limit_bytes{id=\"/\",device=\"/dev/mapper/docker_data\"}) * 100"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 59 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{id=\"/\"}[2m]))"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 59 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_node_status_capacity_cpu_cores)"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 59 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{id=\"/\"})"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 59 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_node_status_capacity_memory_bytes)"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 59 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(container_fs_usage_bytes{id=\"/\",device=\"/dev/mapper/docker_data\"})"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 59 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(container_fs_limit_bytes{id=\"/\",device=\"/dev/mapper/docker_data\"})"
      }
     ]
    },
    {
     "title": "Pod Count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count by (namespace) (kube_pod_info)",
       "legendFormat": "{{ namespace }}"
      }
     ]
    },
    {
     "title": "Container Count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 65 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count by (namespace) (kube_pod_container_info)",
       "legendFormat": "{{ namespace }}"
      }
     ]
    }
   ]
  }
 ]
}