{
 "title": "Kubernetes: Resource Requests",
 "description": "Dashboard to show the resource requests vs allocatable in the cluster",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "CPU Cores",
   "type": "graph",
   "description": "This represents the total [CPU resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu) in the cluster.\nFor comparison the total [allocatable CPU cores](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "CPU Cores" }
   ],
   "targets": [
    {
     "expr": "min(sum(kube_node_status_allocatable_cpu_cores) by (instance))",
     "legendFormat": "Allocatable CPU Cores"
    },
    {
     "expr": "max(sum(kube_pod_container_resource_requests_cpu_cores) by (instance))",
     "legendFormat": "Requested CPU Cores"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(sum(kube_pod_container_resource_requests_cpu_cores) by (instance)) / min(sum(kube_node_status_allocatable_cpu_cores) by (instance)) * 100"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "This represents the total [memory resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-memory) in the cluster.\nFor comparison the total [allocatable memory](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "min(sum(kube_node_status_allocatable_memory_bytes) by (instance))",
     "legendFormat": "Allocatable Memory"
    },
    {
     "expr": "max(sum(kube_pod_container_resource_requests_memory_bytes) by (instance))",
     "legendFormat": "Requested Memory"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(sum(kube_pod_container_resource_requests_memory_bytes) by (instance)) / min(sum(kube_node_status_allocatable_memory_bytes) by (instance)) * 100"
    }
   ]
  },
  {
   "title": "Cluster Pod Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Pod Count" }
   ],
   "targets": [
    { "expr": "sum(kube_pod_info)", "legendFormat": "Current number of Pods" },
    {
     "expr": "sum(kube_node_status_capacity_pods)",
     "legendFormat": "Maximum capacity of pods"
    }
   ]
  },
  {
   "title": "Pod Utilization",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (sum(kube_node_status_capacity_pods) - sum(kube_pod_info)) / sum(kube_node_status_capacity_pods) * 100"
    }
   ]
  }
 ]
}