#!/bin/bash
# Cloud Z CP Public monitoring component installation script
# I will change this script to golang code

usage() {
  cat <<"EOF"
USAGE:
  install -p,--provider         : kubernetes service provider (iks, eks, aks)
  install -a,--access           : ingress access type (private or public)
  install --upgrade             : upgrade mode

  install -h,--help             : show this message
EOF
}

install() {
  local provider="${1}"
  local access="${2}"
  local upgrade=${3}

  # Set variables
  current_context=$(kubectl config current-context)
  if [ "${provider}" = "iks" ]; then
    cluster_name=${current_context%%/*}
  elif [ "${provider}" = "eks" ]; then
    cluster_name=${current_context##*/}
  elif [ "${provider}" = "aks" ]; then
    cluster_name=${current_context}
  fi
  echo "Please check the cluster name, \"${cluster_name}\""
  read -rp "If it is correct, please press ENTER key, otherwise enter the correct cluster name: " input_cluster_name
  if [ "${input_cluster_name}" != "" ]; then
    cluster_name=${input_cluster_name}
  fi
  CLUSTER_NAME=$(echo "${cluster_name}" | tr '[:lower:]' '[:upper:]')

  host_prefix=$(if [ "${cluster_name##*-}" = "dev" ]; then echo "${cluster_name#*-}"; else remainder=${cluster_name#*-}; echo "${remainder%-*}"; fi)

  if [ "${provider}" = "iks" ]; then
    if [ "${access}" = "private" ]; then
      alb_id=$(kubectl get deployment -n kube-system --no-headers=true -o=custom-columns=NAME:.metadata.name | grep "private-.*-alb1")
    elif [ "${access}" = "public" ]; then
      alb_id=$(kubectl get deployment -n kube-system --no-headers=true -o=custom-columns=NAME:.metadata.name | grep "public-.*-alb1")
    fi
  elif [ "${provider}" = "eks" ] || [ "${provider}" = "aks" ]; then
    if [ "${access}" = "private" ]; then
      ingress_class="private-nginx"
    elif [ "${access}" = "public" ]; then
      ingress_class="nginx"
    fi
  fi

  if [ "${provider}" = "iks" ]; then
    # Create ectd secret
    if ! ${upgrade}; then
      kubectl patch secret calico-etcd-secrets -n kube-system -p='{"metadata": {"name": "etcd-secrets", "namespace": "zcp-system"}}' --dry-run -o yaml | kubectl create -f -
    fi
  fi

  mkdir -p .kustomize/"${cluster_name}"
  # Clean up kustomize resources for cluster
  rm -rf .kustomize/"${cluster_name}"/*
  # Copy kustomize overlay resources for cluster from templates
  cp -r templates/common/* .kustomize/"${cluster_name}"
  cp -r templates/"${provider}"/* .kustomize/"${cluster_name}"

  # Patch ingress and config files
  sed -i'.bak' -e 's/${CLUSTER_NAME}/'${CLUSTER_NAME}'/g' .kustomize/"${cluster_name}"/prometheus/config/prometheus.yml

  echo "Please check the subdomain prefix, \"${host_prefix}\""
  read -rp "If it is correct, please press ENTER key, otherwise enter the correct subdomain prefix: " input_host_prefix
  if [ "${input_host_prefix}" != "" ]; then
    host_prefix=${input_host_prefix}
  fi
  sed -i'.bak' -e 's/${HOST_PREFIX}/'${host_prefix}'/g' .kustomize/"${cluster_name}"/grafana/config.properties
  sed -i'.bak' -e 's/${HOST_PREFIX}/'${host_prefix}'/g' .kustomize/"${cluster_name}"/alertmanager/alertmanager-ingress_patch.yaml
  sed -i'.bak' -e 's/${HOST_PREFIX}/'${host_prefix}'/g' .kustomize/"${cluster_name}"/grafana/grafana-ingress_patch.yaml
  sed -i'.bak' -e 's/${HOST_PREFIX}/'${host_prefix}'/g' .kustomize/"${cluster_name}"/prometheus/prometheus-ingress_patch.yaml
  if [ "${provider}" = "iks" ]; then
    echo "Please check the ALB ID \"${alb_id}\""
    read -rp "If it is correct, please press ENTER key, otherwise please enter the correct ALB ID: " input_alb_id
    if [ "${input_alb_id}" != "" ]; then
      alb_id=${input_alb_id}
    fi
    sed -i'.bak' -e 's/${ALB_ID}/'${alb_id}'/g' .kustomize/"${cluster_name}"/ingress_annotations_patch.yaml
  elif [ "${provider}" = "eks" ] || [ "${provider}" = "aks" ]; then
    echo "Please check the ingress class \"${ingress_class}\""
    read -rp "If it is correct, please press ENTER key, otherwise please enter the correct ingress class: " input_ingress_class
    if [ "${input_ingress_class}" != "" ]; then
      ingress_class=${input_ingress_class}
    fi
    sed -i'.bak' -e 's/${INGRESS_CLASS}/'${ingress_class}'/g' .kustomize/"${cluster_name}"/ingress_annotations_patch.yaml
  fi
  read -rp "Please enter the password for alertmanager webhook config: " api_password
  sed -i'.bak' -e 's/${API_PASSWORD}/'${api_password}'/g' .kustomize/"${cluster_name}"/alertmanager/secret.properties

  # Apply kustomize resources
  kubectl kustomize .kustomize/"${cluster_name}"
  while true; do
      read -rp "## Check the above resources before applying. Correct? (y/n): " yn
      case $yn in
          [Yy]* ) echo "It will be applying this resources to your cluster" && break;;
          [Nn]* ) echo "Bye!" && exit;;
      esac
  done
  if ${upgrade}; then
    kubectl apply -k .kustomize/"${cluster_name}" -l'resource-policy!=skip'
    sleep 60
    kubectl exec -it $(kubectl get pod -lcomponent=zcp-alertmanager --no-headers=true -o=custom-columns=NAME:.metadata.name) -- curl -X POST http://alertmanager-service:9093/-/reload
    kubectl exec -it $(kubectl get pod -lcomponent=zcp-alertmanager --no-headers=true -o=custom-columns=NAME:.metadata.name) -- curl -X POST http://prometheus-service:9090/-/reload
  else
    kubectl create -k .kustomize/"${cluster_name}"
  fi
}

main() {
  provider=
  access="private" # Default access is private
  upgrade=false
  while [ "$1" != "" ]; do
    case $1 in
        -p | --provider )       shift
                                provider=$1
                                ;;
        -a | --access )         shift
                                access=$1
                                ;;
        --upgrade )             upgrade=true
                                ;;
        -h | --help )           usage
                                exit
                                ;;
        * )                     usage
                                exit 1
    esac
    shift
  done

  if [ "${provider}" != "iks" ] && [ "${provider}" != "eks" ] && [ "${provider}" != "aks" ]; then
    echo "Provider must be iks, eks or aks"
    exit 1
  fi

  if [ "${access}" != "private" ] && [ "${access}" != "public" ]; then
    echo "Access must be private or public"
    exit 1
  fi
  install "${provider}" "${access}" ${upgrade}
}

main "$@"