#!/bin/bash
# Cloud Z CP Public monitoring component installation script
# I will change this script to golang code

usage() {
  cat <<"EOF"
USAGE:
  install -p,--provider         : kubernetes service provider (iks, eks, aks)
  install -a,--access           : ingress access type (private or public)
  install --upgrade             : upgrade mode

  install -h,--help             : show this message
EOF
}

install() {
  local provider="${1}"
  local access="${2}"
  local upgrade=${3}

  # Set variables
  current_context=$(kubectl config current-context)
  if [ "${provider}" = "iks" ]; then
    cluster_name=${current_context%%/*}
  elif [ "${provider}" = "eks" ]; then
    cluster_name=${current_context##*/}
  elif [ "${provider}" = "aks" ]; then
    cluster_name=${current_context}
  fi
  CLUSTER_NAME=$(echo $cluster_name | tr '[:lower:]' '[:upper:]')
  host_prefix=$(if [ ${cluster_name##*-} = "dev" ]; then echo ${cluster_name#*-}; else remainder=${cluster_name#*-}; echo ${remainder%-*}; fi)

  if [ "${provider}" = "iks" ]; then
    if [ "${access}" = "private" ]; then
      alb_id=$(kubectl get deployment -n kube-system --no-headers=true -o=custom-columns=NAME:.metadata.name | grep "private-.*-alb1")
    elif [ "${access}" = "public" ]; then
      alb_id=$(kubectl get deployment -n kube-system --no-headers=true -o=custom-columns=NAME:.metadata.name | grep "public-.*-alb1")
    fi
  elif [ "${provider}" = "eks" ] || [ "${provider}" = "aks" ]; then
    if [ "${access}" = "private" ]; then
      ingress_class="private-nginx"
    elif [ "${access}" = "public" ]; then
      ingress_class="nginx"
    fi
  fi

  if [ "${provider}" = "iks" ]; then
    # Create ectd secret
    if ! ${upgrade}; then
      kubectl patch secret calico-etcd-secrets -n kube-system -p='{"metadata": {"name": "etcd-secrets", "namespace": "zcp-system"}}' --dry-run -o yaml | kubectl create -f -
    fi
  fi

  mkdir -p .kustomize/${cluster_name}
  # Clean up kustomize resources for cluster
  rm -rf .kustomize/${cluster_name}/*
  # Copy kustomize overlay resources for cluster from templates
  cp templates/kustomization.yaml .kustomize/${cluster_name}
  cp -r templates/${provider} .kustomize/${cluster_name}/upgrade

  # Patch ingress and config files
  sed -i '' 's/CLOUDZCP-TEMPLATE/'${CLUSTER_NAME}'/g' .kustomize/${cluster_name}/upgrade/prometheus/config/prometheus.yml
  sed -i '' 's/template/'${host_prefix}'/g' .kustomize/${cluster_name}/upgrade/grafana/config/grafana.ini
  sed -i '' 's/template/'${host_prefix}'/g' .kustomize/${cluster_name}/upgrade/ingress_patch.yaml
  if [ "${provider}" = "iks" ]; then
    sed -i '' 's/alb_id/'${alb_id}'/g' .kustomize/${cluster_name}/upgrade/ingress_patch.yaml
  elif [ "${provider}" = "eks" ] || [ "${provider}" = "aks" ]; then
    sed -i '' 's/ingress_class/'${ingress_class}'/g' .kustomize/${cluster_name}/upgrade/ingress_patch.yaml
  fi
  read -p "Please input password for alertmanager webhook config: " api_password
  sed -i '' 's/${API_PASSWORD}/'${api_password}'/g' .kustomize/${cluster_name}/upgrade/alertmanager/secret.properties

  # Apply kustomize resources
  if ${upgrade}; then
    kubectl kustomize .kustomize/${cluster_name}/upgrade
  else
    kubectl kustomize .kustomize/${cluster_name}
  fi
  while true; do
      read -p "## Check the above resources before applying. Is it right? (Input y or n): " yn
      case $yn in
          [Yy]* ) echo "It will be applying this resources to your cluster" && break;;
          [Nn]* ) echo "Bye!" && exit;;
      esac
  done
  if ${upgrade}; then
    kubectl apply -k .kustomize/${cluster_name}/upgrade
    sleep 60
    kubectl exec -it $(kubectl get pod -lcomponent=zcp-alertmanager --no-headers=true -o=custom-columns=NAME:.metadata.name) -- curl -X POST http://alertmanager-service:9093/-/reload
    kubectl exec -it $(kubectl get pod -lcomponent=zcp-alertmanager --no-headers=true -o=custom-columns=NAME:.metadata.name) -- curl -X POST http://prometheus-service:9090/-/reload
  else
    kubectl apply -k .kustomize/${cluster_name}
  fi
}

main() {
  provider=
  access="private" # Default access is private
  upgrade=false
  while [ "$1" != "" ]; do
    case $1 in
        -p | --provider )       shift
                                provider=$1
                                ;;
        -a | --access )         shift
                                access=$1
                                ;;
        --upgrade )             upgrade=true
                                ;;
        -h | --help )           usage
                                exit
                                ;;
        * )                     usage
                                exit 1
    esac
    shift
  done

  if [ "${provider}" != "iks" ] && [ "${provider}" != "eks" ] && [ "${provider}" != "aks" ]; then
    echo "Provider must be iks, eks or aks"
    exit 1
  fi

  if [ "${access}" != "private" ] && [ "${access}" != "public" ]; then
    echo "Access must be private or public"
    exit 1
  fi
  install "${provider}" "${access}" ${upgrade}
}

main "$@"