{
 "title": "Kubernetes: Performance Overview",
 "description": "Used to view and monitor Kubernetes performance",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "API Server Requests (Req/Sec)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count[2m]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "API Server Latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "avg(apiserver_request_latencies_sum / apiserver_request_latencies_count)",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Kubelet Pod Start Latency",
   "type": "graph",
   "description": "Latency in microseconds for a single pod to go from pending to running. Broken down by podname.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "rate(kubelet_pod_start_latency_microseconds_sum[5m]) / rate(kubelet_pod_start_latency_microseconds_count[5m])",
     "legendFormat": "kubelet - {{instance}}"
    }
   ]
  },
  {
   "title": "Running Pods Trands",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kubelet_running_pod_count", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Creating Rate of Pods",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kubelet_running_pod_count[2m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Running Containers Trands",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kubelet_running_container_count",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Creating Rate of Containers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kubelet_running_container_count[2m])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}