global:
  # ResolveTimeout is the time after which an alert is declared resolved
  # if it has not been updated.
  resolve_timeout: 5m

  # The smarthost and SMTP sender used for mail notifications.
  smtp_smarthost: 'smtp.sendgrid.net:587'
  smtp_from: 'alertmanager@zcp.com'
  smtp_auth_username: 'foo@bar.com'
  smtp_auth_password: 'barfoo'
  smtp_auth_secret: 'foobar'
  smtp_require_tls: true

  slack_api_url: 'https://global.slack_api_url'
  hipchat_auth_token: '1234556789'
  hipchat_api_url: 'https://hipchat.foobar.org/'

# The directory from which notification templates are read.
templates:
- '/etc/templates/*.tmpl'

# The root route on which each incoming alert enters.
route:

  # The labels by which incoming alerts are grouped together. For example,
  # multiple alerts coming in for cluster=A and alertname=LatencyHigh would
  # be batched into a single group.

  group_by: ['alertname', 'severity', 'receiver', 'priority', 'env', 'product']

  # When a new group of alerts is created by an incoming alert, wait at
  # least 'group_wait' to send the initial notification.
  # This way ensures that you get multiple alerts for the same group that start
  # firing shortly after another are batched together on the first
  # notification.

  group_wait: 30s

  # When the first notification was sent, wait 'group_interval' to send a batch
  # of new alerts that started firing for that group.

  group_interval: 5m

  # If an alert has successfully been sent, wait 'repeat_interval' to
  # resend them.

  repeat_interval: 60m

  # A default receiver

  # If an alert isn't caught by a route, send it to default.
  receiver: default

  # All the above attributes are inherited by all child routes and can
  # overwritten on each.

  # The child route trees.
  routes:
  - receiver: default
    continue: true
  - receiver: alert-aggregator
    continue: true

receivers:
- name: 'default'
  webhook_configs:
  - url: http://zcp-alertmanager-store-svc:5000/webhook
    send_resolved: true

- name: 'alert-aggregator'
  webhook_configs:
  - url: https://api.cloudzcp.io/alert/webhook/alertmanager
    send_resolved: true
    http_config:
      basic_auth:
        username: alertmanager
        password_file: /etc/secrets/API_PASSWORD
