{
 "title": "Kubernetes: POD Overview",
 "tags": [
  "kubernetes",
  "pods"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, pod)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(kube_pod_container_info{namespace=\"$namespace\", pod=~\"$pod\"}, container)"
   }
  ]
 },
 "panels": [
  { "title": "POD Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "POD Count (Namespace)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_info{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "graph",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg(kube_pod_status_phase{namespace=~\"$namespace\",pod=~\"$pod\"}) by(namespace, pod, phase)) by(phase)",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "Pod Restart",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts{namespace=~\"$namespace\", pod=~\"$pod\"} or kube_pod_container_status_restarts_total{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "POD Resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=\"$pod\",container!=\"\"}[2m])) "
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container) (rate(container_cpu_usage_seconds_total{container!=\"\",container=~\"$container\",pod=~\"$pod\"}[2m]))",
     "legendFormat": "Current: {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_requests_cpu_cores{pod=~\"$pod\"}",
     "legendFormat": "Requested: {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{pod=~\"$pod\"}",
     "legendFormat": "Limit: {{ container }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 17 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",pod=\"$pod\",container!=\"\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by(container) (container_memory_working_set_bytes{pod=\"$pod\",container=~\"$container\",container!=\"\"})",
     "legendFormat": "Current: {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_requests_memory_bytes{pod=\"$pod\",container=~\"$container\"}",
     "legendFormat": "Requested: {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{pod=\"$pod\",container=~\"$container\"}",
     "legendFormat": "Limit: {{ container }}"
    }
   ]
  },
  {
   "title": "Volume",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 22 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_used_bytes and on (persistentvolumeclaim) kube_pod_spec_volumes_persistentvolumeclaims_info{pod=\"$pod\"})"
    }
   ]
  },
  {
   "title": "Volume Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kubelet_volume_stats_capacity_bytes and on (persistentvolumeclaim) kube_pod_spec_volumes_persistentvolumeclaims_info{pod=\"$pod\"}",
     "legendFormat": "Capacity : {{ persistentvolumeclaim }}"
    },
    {
     "expr": "kubelet_volume_stats_used_bytes and on (persistentvolumeclaim) kube_pod_spec_volumes_persistentvolumeclaims_info{pod=\"$pod\"}",
     "legendFormat": "Used : {{ persistentvolumeclaim }}"
    }
   ]
  },
  {
   "title": "Filesystem Read/Write",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 27 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{namespace=\"$namespace\",pod=~\"$pod\",container!=\"\"}[2m])) + sum(rate(container_fs_writes_bytes_total{namespace=\"$namespace\",pod=~\"$pod\",container!=\"\"}[2m]))"
    }
   ]
  },
  {
   "title": "Filesystem Read/Write",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (container) (rate(container_fs_reads_bytes_total{namespace=\"$namespace\",pod=\"$pod\",container=~\"$container\",container!=\"\"}[2m]))",
     "legendFormat": "Reads : {{ container }}"
    },
    {
     "expr": "sum by (container) (rate(container_fs_writes_bytes_total{namespace=\"$namespace\",pod=\"$pod\",container=~\"$container\",container!=\"\"}[2m]))",
     "legendFormat": "Writes : {{ container }}"
    }
   ]
  },
  {
   "title": "Network RX/TX",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 32 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\",pod=\"$pod\"}[2m])) + sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\",pod=\"$pod\"}[2m])) "
    }
   ]
  },
  {
   "title": "Network TX/RX",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 32 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{pod=\"$pod\",interface=\"eth0\"}[2m])",
     "legendFormat": "TX : {{ pod }}"
    },
    {
     "expr": "rate(container_network_receive_bytes_total{pod=\"$pod\",interface=\"eth0\"}[2m])",
     "legendFormat": "RX : {{ pod }}"
    }
   ]
  }
 ]
}