apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: zcp-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: prometheus
    spec:
      serviceAccountName: prometheus
      containers:
        - name: prometheus
          image: prom/prometheus:v2.7.0
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 4000m
              memory: 4Gi
            requests:
              cpu: 3000m
              memory: 3Gi
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/data"
            - "--storage.tsdb.retention=30d"
            - "--web.enable-lifecycle"
            - "--web.enable-admin-api"
          ports:
            - containerPort: 9090
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /-/healthy
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 30
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /-/ready
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 30
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
            - name: prometheus-storage-volume
              mountPath: /data
            - name: rules-volume
              mountPath: /etc/prometheus-rules/
            - name: user-rules-volume
              mountPath: /etc/prometheus-user-rules/
            - name: etcd-secrets-volume
              mountPath: /etc/config
              readOnly: true
      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-config
        - name: prometheus-storage-volume
          persistentVolumeClaim:
            claimName: prometheus-data
        - name: rules-volume
          configMap:
            defaultMode: 420
            name: prometheus-rules
        - name: user-rules-volume
          configMap:
            defaultMode: 420
            name: prometheus-user-rules
        - name: etcd-secrets-volume
          secret:
            secretName: etcd-secrets
