{
 "title": "Kubernetes: POD Overview",
 "tags": [
  "kubernetes",
  "pods"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, pod)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(kube_pod_container_info{namespace=\"$namespace\", pod=~\"$pod\"}, container)"
   }
  ]
 },
 "panels": [
  { "title": "POD Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "POD Count (Namespace)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_info{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "graph",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg(kube_pod_status_phase{namespace=~\"$namespace\",pod=~\"$pod\"}) by(namespace, pod, phase)) by(phase)",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "Pod Restart",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts{namespace=~\"$namespace\", pod=~\"$pod\"} or kube_pod_container_status_restarts_total{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "POD Resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",pod_name=\"$pod\",container_name!=\"POD\",container_name!=\"\"}[2m])) "
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container_name) (rate(container_cpu_usage_seconds_total{container_name!=\"\",container_name=~\"$container\",container_name!=\"POD\",pod_name=~\"$pod\"}[2m]))",
     "legendFormat": "Current: {{ container_name }}"
    },
    {
     "expr": "kube_pod_container_resource_requests_cpu_cores{pod=~\"$pod\",container!=\"POD\"}",
     "legendFormat": "Requested: {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{pod=~\"$pod\",container!=\"POD\"}",
     "legendFormat": "Limit: {{ container }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 17 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",pod_name=\"$pod\",container_name!=\"POD\",container_name!=\"\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by(container_name) (container_memory_working_set_bytes{pod_name=\"$pod\",container_name=~\"$container\",container_name!=\"POD\",container_name!=\"\"})",
     "legendFormat": "Current: {{ container_name }}"
    },
    {
     "expr": "kube_pod_container_resource_requests_memory_bytes{pod=\"$pod\",container=~\"$container\"}",
     "legendFormat": "Requested: {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{pod=\"$pod\",container=~\"$container\"}",
     "legendFormat": "Limit: {{ container }}"
    }
   ]
  },
  {
   "title": "Filesystem",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 22 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{namespace=\"$namespace\",pod_name=~\"$pod\",container_name!=\"POD\",container_name!=\"\"}[2m])) + sum(rate(container_fs_writes_bytes_total{namespace=\"$namespace\",pod_name=~\"$pod\",container_name!=\"POD\",container_name!=\"\"}[2m]))"
    }
   ]
  },
  {
   "title": "Filesystem Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (container_name) (rate(container_fs_reads_bytes_total{namespace=\"$namespace\",pod_name=\"$pod\",container_name=~\"$container\",container_name!=\"POD\",container_name!=\"\"}[2m]))",
     "legendFormat": "Reads : {{ container_name }}"
    },
    {
     "expr": "sum by (container_name) (rate(container_fs_writes_bytes_total{namespace=\"$namespace\",pod_name=\"$pod\",container_name=~\"$container\",container_name!=\"POD\",container_name!=\"\"}[2m]))",
     "legendFormat": "Writes : {{ container_name }}"
    }
   ]
  },
  {
   "title": "Network RX/TX Total (bytes/sec)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 27 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\",pod_name=\"$pod\"}[2m])) + sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\",pod_name=\"$pod\"}[2m])) "
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{pod_name=\"$pod\",interface=\"eth0\"}[2m])",
     "legendFormat": "TX : {{ pod_name }}"
    },
    {
     "expr": "rate(container_network_receive_bytes_total{pod_name=\"$pod\",interface=\"eth0\"}[2m])",
     "legendFormat": "RX : {{ pod_name }}"
    }
   ]
  }
 ]
}
{
 "title": "Kubernetes: Deployment Overview",
 "description": "Kubernetes: Deployment Overview",
 "tags": [
  "kubernetes",
  "deployment"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "deployment_namespace",
    "label": "Namespace",
    "query": "label_values(kube_deployment_metadata_generation, namespace)"
   },
   {
    "name": "deployment_name",
    "label": "Deployment",
    "query": "label_values(kube_deployment_metadata_generation{namespace=\"$deployment_namespace\"}, deployment)"
   },
   {
    "name": "pod_name",
    "label": "Pod",
    "query": "label_values(kube_pod_info{namespace=\"$deployment_namespace\",created_by_kind=\"ReplicaSet\",created_by_name=~\"$deployment_name-[-a-z0-9]{7,10}\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "DESIRED",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{namespace=\"$deployment_namespace\",deployment=\"$deployment_name\"}"
    }
   ]
  },
  {
   "title": "AVAILABLE",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{namespace=\"$deployment_namespace\",deployment=\"$deployment_name\"}"
    }
   ]
  },
  {
   "title": "Observed Generation",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kube_deployment_status_observed_generation{deployment=\"$deployment_name\",namespace=\"$deployment_namespace\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Metadata Generation",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kube_deployment_metadata_generation{deployment=\"$deployment_name\",namespace=\"$deployment_namespace\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Deployment Create Time",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 3 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - max(kube_deployment_created{deployment=\"$deployment_name\"})"
    }
   ]
  },
  {
   "title": "Total CPU",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 7, "x": 3, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$deployment_namespace\",pod_name=~\"$pod_name\",container_name!=\"POD\",container_name!=\"\"}[2m]))"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$deployment_namespace\",pod_name=~\"$pod_name\",container_name!=\"POD\",container_name!=\"\"}) "
    }
   ]
  },
  {
   "title": "Total Network",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 3 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$deployment_namespace\",pod_name=~\"$pod_name\"}[5m])) + sum(rate(container_network_receive_bytes_total{namespace=\"$deployment_namespace\",pod_name=~\"$deployment_name.*\"}[5m]))"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (rate(container_cpu_usage_seconds_total{namespace=\"$deployment_namespace\",pod_name=~\"$pod_name\",container_name!=\"POD\",container_name!=\"\"}[2m]))"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (container_memory_working_set_bytes{namespace=\"$deployment_namespace\",pod_name=~\"$pod_name\",container_name!=\"POD\",container_name!=\"\"})",
     "legendFormat": "Current : {{ pod_name }} "
    }
   ]
  },
  {
   "title": "Filesystem Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (rate(container_fs_reads_bytes_total{namespace=\"$deployment_namespace\",pod_name=~\"$pod_name\",container_name!=\"POD\",container_name!=\"\"}[2m]))",
     "legendFormat": "Reads: {{ pod_name }}"
    },
    {
     "expr": "sum by (pod_name) (rate(container_fs_writes_bytes_total{namespace=\"$deployment_namespace\",pod_name=~\"$pod_name\",container_name!=\"POD\",container_name!=\"\"}[2m]))",
     "legendFormat": "Writes: {{ pod_name }}"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (rate(container_network_transmit_bytes_total{namespace=\"$deployment_namespace\",pod_name=~\"$pod_name\"}[2m]))",
     "legendFormat": "TX: {{ pod_name }}"
    },
    {
     "expr": "sum by (pod_name)(rate(container_network_receive_bytes_total{namespace=\"$daemonset_namespace\",pod_name=~\"$pod_name\"}[2m]))",
     "legendFormat": "RX: {{ pod_name }}"
    }
   ]
  },
  {
   "title": "Replica Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(kube_deployment_status_replicas_available{namespace=~\"$deployment_namespace\",deployment=~\"$deployment_name\"}) by(namespace, deployment)",
     "legendFormat": "Available"
    },
    {
     "expr": "avg(kube_deployment_status_replicas_unavailable{namespace=~\"$deployment_namespace\",deployment=~\"$deployment_name\"}) by(namespace, deployment)",
     "legendFormat": "Unavailable"
    },
    {
     "expr": "avg(kube_deployment_status_replicas_updated{namespace=~\"$deployment_namespace\",deployment=~\"$deployment_name\"}) by(namespace, deployment)",
     "legendFormat": "Updated"
    }
   ]
  },
  {
   "title": "Spec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(kube_deployment_spec_replicas{namespace=~\"$deployment_namespace\",deployment=~\"$deployment_name\"}) by(namespace, deployment)",
     "legendFormat": "Replicas"
    },
    {
     "expr": "avg(kube_deployment_spec_paused{namespace=~\"$deployment_namespace\",deployment=~\"$deployment_name\"}) by(namespace, deployment)",
     "legendFormat": "Paused"
    }
   ]
  }
 ]
}
{
 "title": "Kubernetes: DaemonSet Overview",
 "description": "Kubernetes: DaemonSet Overview",
 "tags": [
  "kubernetes",
  "daemonset"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "daemonset_namespace",
    "label": "Namespace",
    "query": "label_values(kube_daemonset_metadata_generation, namespace)"
   },
   {
    "name": "daemonset_name",
    "label": "DaemonSet",
    "query": "label_values(kube_daemonset_metadata_generation{namespace=\"$daemonset_namespace\"}, daemonset)"
   },
   {
    "name": "pod_name",
    "label": "Pod",
    "query": "label_values(kube_pod_info{namespace=\"$daemonset_namespace\",created_by_kind=\"DaemonSet\",created_by_name=\"$daemonset_name\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "DESIRED",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kube_daemonset_status_desired_number_scheduled{daemonset=\"$daemonset_name\",namespace=\"$daemonset_namespace\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "CURRENT",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kube_daemonset_status_current_number_scheduled{daemonset=\"$daemonset_name\",namespace=\"$daemonset_namespace\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "READY",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kube_daemonset_status_number_ready{daemonset=\"$daemonset_name\",namespace=\"$daemonset_namespace\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "AVAILABLE",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(kube_daemonset_status_number_available{daemonset=\"$daemonset_name\",namespace=\"$daemonset_namespace\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Metadata Generation",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kube_daemonset_metadata_generation{daemonset=\"$daemonset_name\",namespace=\"$daemonset_namespace\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "DaemonSet Create Time",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 3 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - max(kube_daemonset_created{daemonset=~\"$daemonset_name\"})"
    }
   ]
  },
  {
   "title": "Total CPU",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 7, "x": 3, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$daemonset_namespace\",pod_name=~\"$pod_name\",container_name!=\"POD\",container_name!=\"\"}[2m]))"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$daemonset_namespace\",pod_name=~\"$pod_name\",container_name!=\"POD\",container_name!=\"\"})"
    }
   ]
  },
  {
   "title": "Total Network",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 3 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$daemonset_namespace\",pod_name=~\"$pod_name\"}[2m])) + sum(rate(container_network_receive_bytes_total{namespace=\"$daemonset_namespace\",pod_name=~\"$pod_name\"}[2m]))"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (rate(container_cpu_usage_seconds_total{namespace=\"$daemonset_namespace\",pod_name=~\"$pod_name\",container_name!=\"POD\",container_name!=\"\"}[2m]))",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (container_memory_working_set_bytes{namespace=\"$daemonset_namespace\",pod_name=~\"$pod_name\",container_name!=\"POD\",container_name!=\"\"})",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Filesystem Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (rate(container_fs_reads_bytes_total{namespace=\"$daemonset_namespace\",pod_name=~\"$pod_name\",container_name!=\"POD\",container_name!=\"\"}[2m]))",
     "legendFormat": "Reads: {{ pod_name }}"
    },
    {
     "expr": "sum by (pod_name) (rate(container_fs_writes_bytes_total{namespace=\"$daemonset_namespace\",pod_name=~\"$pod_name\",container_name!=\"POD\",container_name!=\"\"}[2m]))",
     "legendFormat": "Writes: {{ pod_name }}"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (rate(container_network_transmit_bytes_total{namespace=\"$daemonset_namespace\",pod_name=~\"$pod_name\"}[2m]))",
     "legendFormat": "TX: {{ pod_name }}"
    },
    {
     "expr": "sum by (pod_name)(rate(container_network_receive_bytes_total{namespace=\"$daemonset_namespace\",pod_name=~\"$pod_name\"}[2m]))",
     "legendFormat": "RX: {{ pod_name }}"
    }
   ]
  },
  {
   "title": "Replicas Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg(kube_daemonset_status_number_ready{daemonset=\"$daemonset_name\",namespace=\"$daemonset_namespace\"}) without (instance, pod)",
     "legendFormat": "Ready"
    },
    {
     "expr": "avg(kube_daemonset_status_number_available{daemonset=\"$daemonset_name\",namespace=\"$daemonset_namespace\"}) without (instance, pod)",
     "legendFormat": "Available"
    },
    {
     "expr": "avg(kube_daemonset_status_number_unavailable{daemonset=\"$daemonset_name\",namespace=\"$daemonset_namespace\"}) without (instance, pod)",
     "legendFormat": "Unavailable"
    },
    {
     "expr": "avg(kube_daemonset_status_number_misscheduled{daemonset=\"$daemonset_name\",namespace=\"$daemonset_namespace\"}) without (instance, pod)",
     "legendFormat": "Misscheduled"
    }
   ]
  }
 ]
}
{
 "title": "Kubernetes: StatefulSets Overview",
 "description": "Kubernetes: StatefulSets Overview",
 "tags": [
  "kubernetes",
  "statefulset"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "statefulset_namespace",
    "label": "Namespace",
    "query": "label_values(kube_statefulset_metadata_generation, namespace)"
   },
   {
    "name": "statefulset_name",
    "label": "StatefulSet",
    "query": "label_values(kube_statefulset_metadata_generation{namespace=\"$statefulset_namespace\"}, statefulset)"
   },
   {
    "name": "pod_name",
    "label": "Pod",
    "query": "label_values(kube_pod_info{namespace=\"$statefulset_namespace\",created_by_kind=\"StatefulSet\",created_by_name=\"$statefulset_name\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "DESIRED",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kube_statefulset_replicas{namespace=\"$statefulset_namespace\",statefulset=\"$statefulset_name\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "AVAILABLE",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(kube_statefulset_status_replicas{namespace=\"$statefulset_namespace\",statefulset=\"$statefulset_name\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Observed Generation",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kube_statefulset_status_observed_generation{namespace=\"$statefulset_namespace\",statefulset=\"$statefulset_name\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Metadata Generation",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kube_statefulset_metadata_generation{namespace=\"$statefulset_namespace\",statefulset=\"$statefulset_name\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "StatefulSet Create Time",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 3 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - max(kube_statefulset_created{statefulset=\"$statefulset_name\"})"
    }
   ]
  },
  {
   "title": "Total CPU",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 7, "x": 3, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$statefulset_namespace\",pod_name=~\"$pod_name\",container_name!=\"POD\",container_name!=\"\"}[2m]))"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$statefulset_namespace\",pod_name=~\"$pod_name\",container_name!=\"POD\",container_name!=\"\"})"
    }
   ]
  },
  {
   "title": "Total Network",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 3 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$statefulset_namespace\",pod_name=~\"$statefulset_name.*\",pod_name!=\"\"}[2m])) + sum(rate(container_network_receive_bytes_total{namespace=\"$statefulset_namespace\",pod_name=~\"$statefulset_name.*\", pod_name!=\"\"}[2m]))"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (rate(container_cpu_usage_seconds_total{namespace=\"$statefulset_namespace\",pod_name=~\"$pod_name\",container_name!=\"POD\",container_name!=\"\"}[2m]))",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (container_memory_working_set_bytes{namespace=\"$statefulset_namespace\",pod_name=~\"$pod_name\",container_name!=\"\",container_name!=\"POD\"})",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Filesystem Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (rate(container_fs_reads_bytes_total{namespace=\"$statefulset_namespace\",pod_name=~\"$pod_name\",container_name!=\"POD\",container_name!=\"\"}[2m]))",
     "legendFormat": "Reads: {{ pod_name }}"
    },
    {
     "expr": "sum by (pod_name) (rate(container_fs_writes_bytes_total{namespace=\"$statefulset_namespace\",pod_name=~\"$pod_name\",container_name!=\"POD\",container_name!=\"\"}[2m]))",
     "legendFormat": "Writes: {{ pod_name }}"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (rate(container_network_transmit_bytes_total{namespace=\"$statefulset_namespace\",pod_name=~\"$pod_name\"}[2m]))",
     "legendFormat": "TX: {{ pod_name }}"
    },
    {
     "expr": "sum by (pod_name) (rate(container_network_receive_bytes_total{namespace=\"$statefulset_namespace\",pod_name=~\"$pod_name\"}[2m]))",
     "legendFormat": "RX: {{ pod_name }}"
    }
   ]
  },
  {
   "title": "Replicas Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg(kube_statefulset_status_replicas_current{namespace=\"$statefulset_namespace\",statefulset=\"$statefulset_name\"}) without (instance, pod)",
     "legendFormat": "Current"
    },
    {
     "expr": "avg(kube_statefulset_status_replicas{namespace=\"$statefulset_namespace\",statefulset=\"$statefulset_name\"}) without (instance, pod)",
     "legendFormat": "Available"
    }
   ]
  }
 ]
}