{
 "title": "Kubernetes: Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(kube_node_labels, cluster)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(kube_node_labels{cluster=~\"$cluster\"}, node)"
   }
  ]
 },
 "panels": [
  {
   "title": "Provider",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(count by (cluster) (kube_node_info{cluster!=\"\",provider_id=~\"aws:.*\"}))",
     "legendFormat": "AWS"
    },
    {
     "expr": "count(count by (cluster) (kube_node_info{cluster!=\"\",provider_id=~\"azure:.*\"}))",
     "legendFormat": "Azure"
    },
    {
     "expr": "count(count by (cluster) (kube_node_info{cluster!=\"\",provider_id=~\"ibm:.*\"}))",
     "legendFormat": "IBM"
    }
   ]
  },
  {
   "title": "Number of",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "count(kube_node_info)", "legendFormat": "Nodes" },
    { "expr": "count(kube_namespace_created)", "legendFormat": "Namespaces" }
   ]
  },
  {
   "title": "Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kubelet_running_pod_count)", "legendFormat": "Pod" },
    {
     "expr": "sum(kubelet_running_container_count)",
     "legendFormat": "Container"
    }
   ]
  },
  {
   "title": "Alerts Firing(P1)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\",alertname!=\"DeadMansSwitch\",priority=\"P1\"}) or (1-absent(ALERTS{alertstate=\"firing\",alertname!=\"DeadMansSwitch\",priority=\"P1\"}))",
     "legendFormat": "P1"
    }
   ]
  },
  {
   "title": "Alerts Firing(P2~P5)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 2, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\",alertname!=\"DeadMansSwitch\",priority=\"P2\"}) or (1-absent(ALERTS{alertstate=\"firing\",alertname!=\"DeadMansSwitch\",priority=\"P2\"}))",
     "legendFormat": "P2"
    },
    {
     "expr": "sum(ALERTS{alertstate=\"firing\",alertname!=\"DeadMansSwitch\",priority=\"P3\"}) or (1-absent(ALERTS{alertstate=\"firing\",alertname!=\"DeadMansSwitch\",priority=\"P3\"}))",
     "legendFormat": "P3"
    },
    {
     "expr": "sum(ALERTS{alertstate=\"firing\",alertname!=\"DeadMansSwitch\",priority=\"P4\"}) or (1-absent(ALERTS{alertstate=\"firing\",alertname!=\"DeadMansSwitch\",priority=\"P4\"}))",
     "legendFormat": "P4"
    },
    {
     "expr": "sum(ALERTS{alertstate=\"firing\",alertname!=\"DeadMansSwitch\",priority=\"P5\"}) or (1-absent(ALERTS{alertstate=\"firing\",alertname!=\"DeadMansSwitch\",priority=\"P5\"}))",
     "legendFormat": "P5"
    }
   ]
  },
  {
   "title": "Warning Events",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (cluster) (kubernetes_events{event_type=\"Warning\"})",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Node Ready",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "kube_node_status_condition{cluster=~\"$cluster\",condition=\"Ready\",status=\"false\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node MemoryPressure",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 3 },
   "targets": [
    {
     "expr": "kube_node_status_condition{cluster=~\"$cluster\",node=~\"$node\",condition=\"MemoryPressure\",status=\"true\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Running pod count per node",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5,sum by (instance) (kubelet_running_pod_count))",
     "legendFormat": "{{ instance }} "
    }
   ]
  },
  {
   "title": "Running container count per node",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5,sum by (instance) (kubelet_running_container_count))",
     "legendFormat": "{{ instance }} "
    }
   ]
  },
  {
   "title": "Alerts Firing",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (priority) (ALERTS{alertstate=\"firing\",alertname!=\"DeadMansSwitch\"})",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Warning Events",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 5 },
   "targets": [
    {
     "expr": "topk(100,kubernetes_events{event_type!=\"Normal\"})"
    }
   ]
  },
  {
   "title": "pod status phase",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5,sum by (namespace,phase) (kube_pod_status_phase{phase!~\"Running|Succeeded\"} == 1))",
     "legendFormat": "{{namespace}} {{phase}}"
    }
   ]
  },
  {
   "title": "Node DiskPressure",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "kube_node_status_condition{cluster=~\"$cluster\",node=~\"$node\",condition=\"DiskPressure\",status=\"true\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node PIDPressure",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 10 },
   "targets": [
    {
     "expr": "kube_node_status_condition{cluster=~\"$cluster\",node=~\"$node\",condition=\"PIDPressure\",status=\"true\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Alerts Firing",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "ALERTS{alertstate=\"firing\",alertname!=\"DeadMansSwitch\"}"
    }
   ]
  },
  {
   "title": "Node Unschedulable",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 13 },
   "targets": [
    {
     "expr": "kube_node_spec_unschedulable{cluster=~\"$cluster\",node=~\"$node\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "Resource usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Node CPU usage",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{id=\"/\"}[1m]) / on (cluster,instance) label_join(kube_node_status_allocatable_cpu_cores,\"instance\",\"\",\"node\")",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Most CPU used node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{id=\"/\"}[1m]) / on (cluster,instance) label_join(kube_node_status_allocatable_cpu_cores,\"instance\",\"\",\"node\")",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Most CPU usage namespace",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,sum by (cluster,namespace) (rate(container_cpu_usage_seconds_total{container!=\"\",container!=\"POD\"}[1m])))",
     "legendFormat": "{{ namespace }} "
    }
   ]
  },
  {
   "title": "Node memory usage",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{id=\"/\"} / on (instance) label_join(kube_node_status_allocatable_memory_bytes,\"instance\",\"\",\"node\")",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Most CPU used node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{id=\"/\"}[1m]) / on (cluster,instance) label_join(kube_node_status_allocatable_cpu_cores,\"instance\",\"\",\"node\")",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Most Memory usage namespace",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,sum by (cluster,namespace) (container_memory_working_set_bytes{container!=\"\",container!=\"POD\"}))",
     "legendFormat": "{{namespace}}@{{cluster}}"
    }
   ]
  },
  {
   "title": "Most CPU used node",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,((rate(container_cpu_usage_seconds_total{id=\"/\"}[1m])) / on (cluster,instance) label_join(kube_node_status_allocatable_cpu_cores,\"instance\",\"\",\"node\")))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Most CPU-intensive pods",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,sum by (cluster,namespace,pod) (rate(container_cpu_usage_seconds_total{container!=\"\",container!=\"POD\"}[1m])))",
     "legendFormat": "{{pod}}@{{cluster}}"
    }
   ]
  },
  {
   "title": "Container memory usage(Top 10)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(10,container_memory_working_set_bytes{container!=\"\",container!=\"POD\"} / on (cluster,namespace,container,pod) group_left  container_spec_memory_limit_bytes{container!=\"\",container!=\"POD\"} != +Inf)",
     "legendFormat": "{{container}}@{{pod}}"
    }
   ]
  },
  {
   "title": "Most memory-intensive pods",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,sum by (pod) (container_memory_working_set_bytes{container!=\"\",container!=\"POD\"}))",
     "legendFormat": "{{pod}} "
    }
   ]
  },
  {
   "title": "Disk & Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true
  },
  {
   "title": "Node local disk usage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,container_fs_usage_bytes{id=\"/\",device=~\"/dev/mapper/docker_data|/dev/nvme0n1p1|/dev/sda1\"} / container_fs_limit_bytes)",
     "legendFormat": "{{ instance }} "
    }
   ]
  },
  {
   "title": "Top filesystem reads",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,sum by (instance) (rate(container_fs_reads_bytes_total{id=\"/\",device=~\"/dev/mapper/docker_data|/dev/nvme0n1|/dev/sda\"}[1m])))",
     "legendFormat": "{{ instance }} "
    }
   ]
  },
  {
   "title": "Top network receive",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,sum by (instance) (rate(container_network_receive_bytes_total{id=\"/\"}[1m])))",
     "legendFormat": "{{ instance }} "
    }
   ]
  },
  {
   "title": "Top network transmit",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,sum by (instance) (rate(container_network_transmit_bytes_total{id=\"/\"}[1m])))",
     "legendFormat": "{{ instance }} "
    }
   ]
  },
  {
   "title": "Persistent volume usage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,sum by (cluster,persistentvolumeclaim) (kubelet_volume_stats_used_bytes / kubelet_volume_stats_capacity_bytes))",
     "legendFormat": "{{persistentvolumeclaim}}@{{cluster}}"
    }
   ]
  },
  {
   "title": "Top filesystem writes",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,sum by (instance) (rate(container_fs_writes_bytes_total{id=\"/\",device=~\"/dev/mapper/docker_data|/dev/nvme0n1|/dev/sda\"}[1m])))",
     "legendFormat": "{{ instance }} "
    }
   ]
  },
  {
   "title": "network receive errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(container_network_receive_errors_total{id=\"/\"}[1m]))",
     "legendFormat": "{{ instance }} "
    }
   ]
  },
  {
   "title": "network transmit errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(container_network_transmit_errors_total{id=\"/\"}[1m]))",
     "legendFormat": "{{ instance }} "
    }
   ]
  }
 ]
}