apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zcp-system
bases:
- ../../base
patchesStrategicMerge:
- prometheus/prometheus-ingress.yaml
- prometheus/prometheus-pvc.yaml
- grafana/grafana-pvc.yaml
- grafana/grafana-ingress.yaml
- alertmanager/alertmanager-ingress.yaml
