bases:
- ../../base
patchesStrategicMerge:
- prometheus/prometheus-ingress.yaml
- prometheus/prometheus-pvc.yaml
- grafana/grafana-pvc.yaml
- grafana/grafana-ingress.yaml
- alertmanager/alertmanager-ingress.yaml