{
 "title": "Kubernetes: Cluster-Namespaces Overview",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(kube_node_labels, cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_namespace_created{cluster=\"$cluster\"}, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_node_info{cluster=\"$cluster\"})",
     "legendFormat": "Nodes"
    },
    {
     "expr": "count(kube_namespace_created{cluster=\"$cluster\"})",
     "legendFormat": "Namespaces"
    }
   ]
  },
  {
   "title": "Running",
   "type": "stat",
   "gridPos": { "h": 6, "w": 21, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_running_pod_count{cluster=\"$cluster\",namespace=\"$namespace\"})",
     "legendFormat": "Pod"
    },
    {
     "expr": "sum(kubelet_running_container_count{cluster=\"$cluster\",namespace=\"$namespace\"})",
     "legendFormat": "Container"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores{cluster=\"$cluster\",namespace=~\"$namespace\"})",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "sum(kube_node_status_capacity_cpu_cores{cluster=\"$cluster\",node=~\"$node\"})",
     "legendFormat": "Capacity"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",id=\"/\",instance=~\"$node\"}[2m]))",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "$node CPU Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{cluster=\"$cluster\",instance=~\"$node\",id=\"/\"}[1m])) / sum(kube_node_status_allocatable_cpu_cores{cluster=\"$cluster\",node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "$namespace CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "core" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace) (irate(container_cpu_usage_seconds_total{cluster=\"$cluster\",namespace=~\"$namespace\",container!=\"\",container!=\"POD\"}[1m]))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "$namespace Memory WorkingSet",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace) (container_memory_working_set_bytes{cluster=\"$cluster\",namespace=~\"$namespace\",container!=\"\",container!=\"POD\"})",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_memory_bytes{cluster=\"$cluster\",node=~\"$node\"})",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "sum(kube_node_status_capacity_memory_bytes{cluster=\"$cluster\",node=~\"$node\"})",
     "legendFormat": "Capacity"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\",instance=~\"$node\",id=\"/\"})",
     "legendFormat": "WorkingSet"
    }
   ]
  },
  {
   "title": "$node Memory Usage(WorkingSet/Allocatable)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\",instance=~\"$node\",id=\"/\"}) / sum(kube_node_status_allocatable_memory_bytes{cluster=\"$cluster\",node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Filesystem Reads/Writes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace) (rate(container_fs_reads_bytes_total{cluster=\"$cluster\",container!=\"\",container!=\"POD\",device=~\"/dev/.*\"}[1m]))",
     "legendFormat": "Reads : {{ namespace }}"
    },
    {
     "expr": "sum by (namespace) (rate(container_fs_writes_bytes_total{cluster=\"$cluster\",container!=\"\",container!=\"POD\",device=~\"/dev/.*\"}[1m]))",
     "legendFormat": "Writes : {{ namespace }}"
    }
   ]
  },
  {
   "title": "Network TX/RX",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace) (rate(container_network_transmit_bytes_total{cluster=\"$cluster\",namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "TX : {{ namespace }}"
    },
    {
     "expr": "sum by (namespace) (rate(container_network_receive_bytes_total{cluster=\"$cluster\",namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "RX : {{ namespace }}"
    }
   ]
  },
  {
   "title": "Filesystem",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_fs_limit_bytes{cluster=\"$cluster\",instance=~\"$node\",id=\"/\",device=~\"/dev/mapper/docker_data|/dev/nvme0n1p1|/dev/sda1\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(container_fs_usage_bytes{cluster=\"$cluster\",instance=~\"$node\",id=\"/\",device=~\"/dev/mapper/docker_data|/dev/nvme0n1p1|/dev/sda1\"})",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "$node Filesystem Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{cluster=\"$cluster\",instance=~\"$node\",id=\"/\",device=~\"/dev/mapper/docker_data|/dev/nvme0n1p1|/dev/sda1\"}) / sum(container_fs_limit_bytes{cluster=\"$cluster\",instance=~\"$node\",id=\"/\",device=~\"/dev/mapper/docker_data|/dev/nvme0n1p1|/dev/sda1\"})"
    }
   ]
  },
  {
   "title": "Pod Count",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (namespace) (kube_pod_info{cluster=\"$cluster\"})",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Pod Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (namespace) (kube_pod_info{cluster=\"$cluster\",namespace=~\"$namespace\"})",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Pod Count",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (namespace) (kube_pod_container_info{cluster=\"$cluster\"})",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Container Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (namespace) (kube_pod_container_info{cluster=\"$cluster\",namespace=~\"$namespace\"})",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "$node Memory Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace) (container_memory_working_set_bytes{cluster=\"$cluster\",namespace=~\"$namespace\",container!=\"\",container!=\"POD\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "$node Filesystem Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_fs_usage_bytes{cluster=\"$cluster\",instance=~\"$node\",id=\"/\",device=~\"/dev/mapper/docker_data|/dev/nvme0n1p1|/dev/sda1\"} / container_fs_limit_bytes",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "$namespace Resource Quota",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_resourcequota{cluster=\"$cluster\",namespace=\"$namespace\",resource=\"requests.cpu\",type=\"hard\"}",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Pod Count",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (priority) (ALERTS{cluster=\"$cluster\",alertstate=\"firing\"})",
     "legendFormat": "{{ priority }}"
    }
   ]
  }
 ]
}