{
 "title": "Kubernetes: Node Overview",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(kube_node_info, cluster)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(kube_node_info{cluster=\"$cluster\"}, node)"
   },
   {
    "name": "role",
    "label": "Role",
    "query": "label_values(kube_node_labels, label_role)"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Age",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - kube_node_created{cluster=\"$cluster\",node=\"$node\"}"
    }
   ]
  },
  {
   "title": "Ready?",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_node_status_condition{cluster=\"$cluster\",node=\"$node\",condition=\"Ready\",status=\"true\"}"
    }
   ]
  },
  {
   "title": "Unschedulable?",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_node_spec_unschedulable{cluster=\"$cluster\",node=\"$node\"}"
    }
   ]
  },
  {
   "title": "Memory Pressure?",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_node_status_condition{cluster=\"$cluster\",node=\"$node\",condition=\"MemoryPressure\",status=\"true\"}"
    }
   ]
  },
  {
   "title": "Disk Pressure?",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_node_status_condition{cluster=\"$cluster\",node=\"$node\",condition=\"DiskPressure\",status=\"true\"}"
    }
   ]
  },
  {
   "title": "PID Pressure?",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_node_status_condition{cluster=\"$cluster\",node=\"$node\",condition=\"PIDPressure\",status=\"true\"}"
    }
   ]
  },
  {
   "title": "Pod Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{cluster=\"$cluster\",node=\"$node\"})"
    }
   ]
  },
  {
   "title": "Container Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count (kube_pod_container_info and on (pod) kube_pod_info{cluster=\"$cluster\",node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(container_cpu_usage_seconds_total{cluster=\"$cluster\",instance=\"$node\",id=\"/\"}[1m]) / on (instance) label_join(kube_node_status_allocatable_cpu_cores,\"instance\",\"\",\"node\")"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{instance=\"$node\",id=\"/\"} / on (instance) label_join(kube_node_status_allocatable_memory_bytes,\"instance\",\"\",\"node\")"
    }
   ]
  },
  {
   "title": "Filesystem Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_fs_usage_bytes{cluster=\"$cluster\",instance=\"$node\",id=\"/\",device=~\"/dev/mapper/docker_data|/dev/nvme0n1p1\"} / container_fs_limit_bytes{cluster=\"$cluster\",instance=\"$node\",id=\"/\",device=~\"/dev/mapper/docker_data|/dev/nvme0n1p1\"}"
    }
   ]
  },
  {
   "title": "Filesystem Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_fs_usage_bytes{cluster=\"$cluster\",instance=\"$node\",id=\"/\",device=\"/dev/xvda2\"} / container_fs_limit_bytes{cluster=\"$cluster\",instance=\"$node\",id=\"/\",device=\"/dev/xvda2\"}"
    }
   ]
  },
  {
   "title": "CPU (Usage/Allocatable)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(container_cpu_usage_seconds_total{cluster=\"$cluster\",instance=\"$node\",id=\"/\"}[1m]) / on (instance) label_join(kube_node_status_allocatable_cpu_cores,\"instance\",\"\",\"node\")"
    }
   ]
  },
  {
   "title": "Memory(Usage/Allocatable)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{instance=\"$node\",id=\"/\"} / on (instance) label_join(kube_node_status_allocatable_memory_bytes,\"instance\",\"\",\"node\")"
    }
   ]
  },
  {
   "title": "Filesystem(Overlay) usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 13 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "container_fs_usage_bytes{cluster=\"$cluster\",instance=\"$node\",id=\"/\",device=~\"/dev/mapper/docker_data|/dev/nvme0n1p1\"} / container_fs_limit_bytes{cluster=\"$cluster\",instance=\"$node\",id=\"/\",device=~\"/dev/mapper/docker_data|/dev/nvme0n1p1\"}"
    }
   ]
  },
  {
   "title": "Filesystem(Local) usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 13 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "container_fs_usage_bytes{cluster=\"$cluster\",instance=\"$node\",id=\"/\",device=\"/dev/xvda2\"} / container_fs_limit_bytes{cluster=\"$cluster\",instance=\"$node\",id=\"/\",device=\"/dev/xvda2\"}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "CPU usage(cores)" }
   ],
   "targets": [
    {
     "expr": "irate(container_cpu_usage_seconds_total{cluster=\"$cluster\",instance=\"$node\",id=\"/\"}[1m]) / on (instance) label_join(kube_node_status_allocatable_cpu_cores,\"instance\",\"\",\"node\")",
     "legendFormat": "Rate(Usage/Allocatable)"
    },
    {
     "expr": "kube_node_status_capacity_cpu_cores{cluster=\"$cluster\",node=\"$node\"}",
     "legendFormat": "Capacity"
    },
    {
     "expr": "kube_node_status_allocatable_cpu_cores{node=\"$node\"}",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "irate(container_cpu_usage_seconds_total{cluster=\"$cluster\",instance=\"$node\",id=\"/\"}[1m])",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "bytes", "label": "Memory usage(bytes)" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{cluster=\"$cluster\",instance=\"$node\",id=\"/\"} / on (instance) label_join(kube_node_status_allocatable_memory_bytes,\"instance\",\"\",\"node\")",
     "legendFormat": "Rate(WorkingSet/Allocatable)"
    },
    {
     "expr": "kube_node_status_capacity_memory_bytes{cluster=\"$cluster\",node=\"$node\"}",
     "legendFormat": "Capacity"
    },
    {
     "expr": "kube_node_status_allocatable_memory_bytes{cluster=\"$cluster\",node=\"$node\"}",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "container_memory_usage_bytes{cluster=\"$cluster\",instance=\"$node\",id=\"/\"}",
     "legendFormat": "Usage"
    },
    {
     "expr": "container_memory_working_set_bytes{cluster=\"$cluster\",instance=\"$node\",id=\"/\"}",
     "legendFormat": "WorkingSet"
    },
    {
     "expr": "container_memory_rss{cluster=\"$cluster\",instance=\"$node\",id=\"/\"}",
     "legendFormat": "RSS"
    },
    {
     "expr": "container_memory_cache{cluster=\"$cluster\",instance=\"$node\",id=\"/\"}",
     "legendFormat": "Cache"
    },
    {
     "expr": "container_memory_swap{cluster=\"$cluster\",instance=\"$node\",id=\"/\"}",
     "legendFormat": "Swap"
    },
    {
     "expr": "container_memory_rss{cluster=\"$cluster\",instance=\"$node\",id=\"/\"} + container_memory_cache{cluster=\"$cluster\",instance=\"$node\",id=\"/\"} + container_memory_swap{cluster=\"$cluster\",instance=\"$node\",id=\"/\"}",
     "legendFormat": "RSS+Cache+Swap"
    }
   ]
  },
  {
   "title": "CPU Allocation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "CPU usage(cores)" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (kube_pod_container_resource_requests_cpu_cores{cluster=\"$cluster\",node=\"$node\"}) / on (node) kube_node_status_allocatable_cpu_cores",
     "legendFormat": "Allocated CPU Requests(%)"
    },
    {
     "expr": "sum by (node) (kube_pod_container_resource_limits_cpu_cores{cluster=\"$cluster\",node=\"$node\"}) / on (node) kube_node_status_allocatable_cpu_cores",
     "legendFormat": "Allocated CPU Limits(%)"
    },
    {
     "expr": "kube_node_status_allocatable_cpu_cores{node=\"$node\"}",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{cluster=\"$cluster\",node=\"$node\"})",
     "legendFormat": "Allocated Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{cluster=\"$cluster\",node=\"$node\"})",
     "legendFormat": "Allocated Limits"
    }
   ]
  },
  {
   "title": "Memory Allocation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "bytes", "label": "Memory usage(bytes)" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (kube_pod_container_resource_requests_memory_bytes{cluster=\"$cluster\",node=\"$node\"}) / on (node) kube_node_status_allocatable_memory_bytes",
     "legendFormat": "Allocated Requests(%)"
    },
    {
     "expr": "sum by (node) (kube_pod_container_resource_limits_memory_bytes{cluster=\"$cluster\",node=\"$node\"}) / on (node) kube_node_status_allocatable_memory_bytes",
     "legendFormat": "Allocated Limits(%)"
    },
    {
     "expr": "kube_node_status_allocatable_memory_bytes{cluster=\"$cluster\",node=\"$node\"}",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{cluster=\"$cluster\",node=\"$node\"})",
     "legendFormat": "Allocated Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{cluster=\"$cluster\",node=\"$node\"})",
     "legendFormat": "Allocated Limits"
    }
   ]
  },
  {
   "title": "Filesystem(Overlay) Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_fs_usage_bytes{cluster=\"$cluster\",instance=\"$node\",id=\"/\",device=~\"/dev/mapper/docker_data|/dev/nvme0n1p1\"} / container_fs_limit_bytes{cluster=\"$cluster\",instance=\"$node\",id=\"/\",device=~\"/dev/mapper/docker_data|/dev/nvme0n1p1\"}",
     "legendFormat": "Rate"
    },
    {
     "expr": "container_fs_limit_bytes{cluster=\"$cluster\",instance=\"$node\",id=\"/\",device=~\"/dev/mapper/docker_data|/dev/nvme0n1p1\"}",
     "legendFormat": "Limit"
    },
    {
     "expr": "container_fs_usage_bytes{cluster=\"$cluster\",instance=\"$node\",id=\"/\",device=~\"/dev/mapper/docker_data|/dev/nvme0n1p1\"}",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Filesystem(Local) Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_fs_usage_bytes{cluster=\"$cluster\",instance=\"$node\",id=\"/\",device=\"/dev/xvda2\"} / container_fs_limit_bytes{cluster=\"$cluster\",instance=\"$node\",id=\"/\",device=\"/dev/xvda2\"}",
     "legendFormat": "Rate"
    },
    {
     "expr": "container_fs_limit_bytes{cluster=\"$cluster\",instance=\"$node\",id=\"/\",device=\"/dev/xvda2\"}",
     "legendFormat": "Limit"
    },
    {
     "expr": "container_fs_usage_bytes{cluster=\"$cluster\",instance=\"$node\",id=\"/\",device=\"/dev/xvda2\"}",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Network RX/TX",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{cluster=\"$cluster\",id=\"/\",instance=\"$node\"}[1m])",
     "legendFormat": "RX : {{ interface }}"
    },
    {
     "expr": "-rate(container_network_transmit_bytes_total{cluster=\"$cluster\",id=\"/\",instance=\"$node\"}[1m])",
     "legendFormat": "TX : {{ interface }}"
    }
   ]
  },
  {
   "title": "Pods allocation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_node_status_capacity_pods{cluster=\"$cluster\",node=\"$node\"}",
     "legendFormat": "Capacity"
    },
    {
     "expr": "kube_node_status_allocatable_pods{cluster=\"$cluster\",node=\"$node\"}",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "kubelet_running_pod_count{cluster=\"$cluster\",instance=\"$node\"}",
     "legendFormat": "Allocation"
    }
   ]
  },
  {
   "title": "CPU usage of kubelet, runtime(containerd/dockerd) ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(container_cpu_usage_seconds_total{cluster=\"$cluster\",instance=\"$node\",id=~\"/podruntime/kubelet|/system.slice/kubelet.service\"}[1m])",
     "legendFormat": "{{ id }}"
    },
    {
     "expr": "irate(container_cpu_usage_seconds_total{cluster=\"$cluster\",instance=~\"$node\",id=~\"/podruntime/runtime|/system.slice/docker.service\"}[1m])",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  {
   "title": "Memory usage of kubelet, runtime(containerd/dockerd) ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{cluster=\"$cluster\",instance=\"$node\",id=~\"/podruntime/kubelet|/system.slice/kubelet.service\"}",
     "legendFormat": "Working Set: {{ id }}"
    },
    {
     "expr": "container_memory_rss{cluster=\"$cluster\",instance=\"$node\",id=~\"/podruntime/kubelet|/system.slice/kubelet.service\"}",
     "legendFormat": "RSS: {{ id }}"
    },
    {
     "expr": "container_memory_working_set_bytes{cluster=\"$cluster\",instance=\"$node\",id=~\"/podruntime/runtime|/system.slice/docker.service\"}",
     "legendFormat": "Working Set: {{ id }}"
    },
    {
     "expr": "container_memory_rss{cluster=\"$cluster\",instance=\"$node\",id=~\"/podruntime/runtime|/system.slice/docker.service\"}",
     "legendFormat": "RSS: {{ id }}"
    }
   ]
  },
  {
   "title": "Pods, Containers, Kubelet, Runtime(Containerd, Dockerd)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 }
  },
  {
   "title": "CPU usage of pods",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{cluster=\"$cluster\",instance=\"$node\",container!=\"\",container!=\"POD\"}[1m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by (pod) (irate(container_cpu_usage_seconds_total{cluster=\"$cluster\",instance=\"$node\",container!=\"\",container!=\"POD\"}[1m]))",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "irate(container_cpu_usage_seconds_total{cluster=\"$cluster\",instance=\"$node\",id=~\"/podruntime/kubelet|/system.slice/kubelet.service\"}[1m])",
     "legendFormat": "{{ id }}"
    },
    {
     "expr": "irate(container_cpu_usage_seconds_total{cluster=\"$cluster\",instance=\"$node\",id=~\"/podruntime/runtime|/system.slice/docker.service\"}[1m])",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  {
   "title": "Memory working set of pods",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{cluster=\"$cluster\",instance=\"$node\",id=\"/kubepods\"}) + sum (container_memory_working_set_bytes{cluster=\"$cluster\",instance=\"$node\",id=~\"/podruntime/kubelet|/system.slice/kubelet.service\"}) + sum(container_memory_working_set_bytes{cluster=\"$cluster\",instance=\"$node\",id=~\"/podruntime/runtime|/system.slice/docker.service\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{cluster=\"$cluster\",instance=\"$node\",container!=\"\",container!=\"POD\"})",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "container_memory_working_set_bytes{cluster=\"$cluster\",instance=\"$node\",id=~\"/podruntime/kubelet|/system.slice/kubelet.service\"}",
     "legendFormat": "{{ id }}"
    },
    {
     "expr": "container_memory_working_set_bytes{cluster=\"$cluster\",instance=\"$node\",id=~\"/podruntime/runtime|/system.slice/docker.service\"}",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  {
   "title": "Filesystem usage of pods",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_fs_reads_bytes_total{cluster=\"$cluster\",instance=\"$node\",container_name!=\"\",container_name!=\"POD\"}[1m]))",
     "legendFormat": "Reads: {{ pod }}"
    },
    {
     "expr": "sum by (pod) (rate(container_fs_writes_bytes_total{cluster=\"$cluster\",instance=\"$node\",container_name!=\"\",container_name!=\"POD\"}[1m]))",
     "legendFormat": "Writes: {{ pod }}"
    },
    {
     "expr": "irate(container_fs_reads_bytes_total{cluster=\"$cluster\",instance=\"$node\",id=~\"/podruntime/kubelet|/system.slice/kubelet.service\"}[1m])",
     "legendFormat": "Reads: {{ id }}"
    },
    {
     "expr": "irate(container_fs_writes_bytes_total{cluster=\"$cluster\",instance=\"$node\",id=~\"/podruntime/kubelet|/system.slice/kubelet.service\"}[1m])",
     "legendFormat": "Writes: {{ id }}"
    },
    {
     "expr": "irate(container_fs_reads_bytes_total{cluster=\"$cluster\",instance=\"$node\",id=~\"/podruntime/runtime|/system.slice/docker.service\"}[1m])",
     "legendFormat": "Reads: {{ id }}"
    },
    {
     "expr": "irate(container_fs_writes_bytes_total{cluster=\"$cluster\",instance=\"$node\",id=~\"/podruntime/runtime|/system.slice/docker.service\"}[1m])",
     "legendFormat": "Writes: {{ id }}"
    }
   ]
  },
  {
   "title": "Memory rss of pods",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (container_memory_rss{instance=\"$node\",container_name!=\"POD\",container_name!=\"\"})",
     "legendFormat": "{{ pod_name }}"
    },
    {
     "expr": "sum (container_memory_rss{instance=\"$node\",container_name!=\"POD\",container_name!=\"\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Network usage of pods",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_network_receive_bytes_total{cluster=\"$cluster\",instance=\"$node\",interface=\"eth0\",container=\"POD\"}[1m]))",
     "legendFormat": "RX: {{ pod }}"
    },
    {
     "expr": "-sum by (pod) (rate(container_network_transmit_bytes_total{cluster=\"$cluster\",instance=\"$node\",interface=\"eth0\",container=\"POD\"}[1m]))",
     "legendFormat": "TX: {{ pod }}"
    },
    {
     "expr": "irate(container_network_receive_bytes_total{cluster=\"$cluster\",instance=\"$node\",id=~\"/podruntime/kubelet|/system.slice/kubelet.service\"}[1m])",
     "legendFormat": "RX: {{ id }}"
    },
    {
     "expr": "- irate(container_network_receive_bytes_total{cluster=\"$cluster\",instance=\"$node\",id=~\"/podruntime/kubelet|/system.slice/kubelet.service\"}[1m])",
     "legendFormat": "TX: {{ id }}"
    },
    {
     "expr": "irate(container_network_receive_bytes_total{cluster=\"$cluster\",instance=\"$node\",id=~\"/podruntime/kubelet|/system.slice/kubelet.service\"}[1m])",
     "legendFormat": "RX: {{ id }}"
    },
    {
     "expr": "- irate(container_network_receive_bytes_total{cluster=\"$cluster\",instance=\"$node\",id=~\"/podruntime/kubelet|/system.slice/kubelet.service\"}[1m])",
     "legendFormat": "TX: {{ id }}"
    }
   ]
  },
  {
   "title": "Container Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (namespace) (kube_pod_container_info and on (pod) kube_pod_info{node=~\"$node\"})",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Pod Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (namespace) (kube_pod_info{cluster=\"$cluter\",node=\"$node\"})",
     "legendFormat": "{{ namespace }}"
    }
   ]
  }
 ]
}