{
 "title": "Kubernetes: Cluster-Nodes Overview",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(kube_node_labels, cluster)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(kube_node_labels{cluster=\"$cluster\"}, node)"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_info{cluster=\"$cluster\"})",
     "legendFormat": "Nodes"
    },
    {
     "expr": "count(kube_namespace_created{cluster=\"$cluster\"})",
     "legendFormat": "Namespaces"
    }
   ]
  },
  {
   "title": "Running",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_running_pod_count{cluster=\"$cluster\"})",
     "legendFormat": "Pod"
    },
    {
     "expr": "sum(kubelet_running_container_count{cluster=\"$cluster\"})",
     "legendFormat": "Container"
    }
   ]
  },
  {
   "title": "Unschedulable",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{cluster=\"$cluster\",condition=\"Ready\",status!=\"true\"})",
     "legendFormat": "Not Ready"
    },
    {
     "expr": "sum(kube_node_status_condition{cluster=\"$cluster\",condition=\"MemoryPressure\",status=\"true\"})",
     "legendFormat": "Memory Pressure"
    },
    {
     "expr": "sum(kube_node_status_condition{cluster=\"$cluster\",condition=\"DiskPressure\",status=\"true\"})",
     "legendFormat": "Disk Pressure"
    },
    {
     "expr": "sum(kube_node_status_condition{cluster=\"$cluster\",condition=\"PIDPressure\",status=\"true\"})",
     "legendFormat": "PID Pressure"
    }
   ]
  },
  {
   "title": "Alerts Firing(P1)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{cluster=\"$cluster\",alertstate=\"firing\",alertname!=\"DeadMansSwitch\",priority=\"P1\"}) or (1-absent(sum(ALERTS{cluster=\"$cluster\",alertstate=\"firing\",alertname!=\"DeadMansSwitch\",priority=\"P1\"})))",
     "legendFormat": "P1"
    }
   ]
  },
  {
   "title": "Alerts Firing(P2~P5)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{cluster=\"$cluster\",alertstate=\"firing\",alertname!=\"DeadMansSwitch\",priority=\"P2\"}) or (1-absent(sum(ALERTS{cluster=\"$cluster\",alertstate=\"firing\",alertname!=\"DeadMansSwitch\",priority=\"P2\"})))",
     "legendFormat": "P2"
    },
    {
     "expr": "sum(ALERTS{cluster=\"$cluster\",alertstate=\"firing\",alertname!=\"DeadMansSwitch\",priority=\"P3\"}) or (1-absent(sum(ALERTS{cluster=\"$cluster\",alertstate=\"firing\",alertname!=\"DeadMansSwitch\",priority=\"P3\"})))",
     "legendFormat": "P3"
    },
    {
     "expr": "sum(ALERTS{cluster=\"$cluster\",alertstate=\"firing\",alertname!=\"DeadMansSwitch\",priority=\"P4\"}) or (1-absent(sum(ALERTS{cluster=\"$cluster\",alertstate=\"firing\",alertname!=\"DeadMansSwitch\",priority=\"P4\"})))",
     "legendFormat": "P4"
    },
    {
     "expr": "sum(ALERTS{cluster=\"$cluster\",alertstate=\"firing\",alertname!=\"DeadMansSwitch\",priority=\"P5\"}) or (1-absent(sum(ALERTS{cluster=\"$cluster\",alertstate=\"firing\",alertname!=\"DeadMansSwitch\",priority=\"P5\"})))",
     "legendFormat": "P5"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores{cluster=\"$cluster\",node=~\"$node\"})",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "sum(kube_node_status_capacity_cpu_cores{cluster=\"$cluster\",node=~\"$node\"})",
     "legendFormat": "Capacity"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",id=\"/\",instance=~\"$node\"}[1m]))",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",instance=~\"$node\",id=\"/\"}[1m])) / sum(kube_node_status_allocatable_cpu_cores{cluster=\"$cluster\",node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",id=\"/\",instance=~\"$node\"}[1m])) / on (instance) label_join(kube_node_status_allocatable_cpu_cores{cluster=\"$cluster\"},\"instance\",\"\",\"node\")",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",id=\"/\",instance=~\"$node\"}[1m])) / on (instance) label_join(kube_node_status_allocatable_cpu_cores{cluster=\"$cluster\"},\"instance\",\"\",\"node\")",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_memory_bytes{cluster=\"$cluster\",node=~\"$node\"})",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "sum(kube_node_status_capacity_memory_bytes{cluster=\"$cluster\",node=~\"$node\"})",
     "legendFormat": "Capacity"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\",instance=~\"$node\",id=\"/\"})",
     "legendFormat": "WorkingSet"
    }
   ]
  },
  {
   "title": "Memory Usage(WorkingSet/Allocatable)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\",instance=~\"$node\",id=\"/\"}) / sum(kube_node_status_allocatable_memory_bytes{cluster=\"$cluster\",node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (container_memory_working_set_bytes{cluster=\"$cluster\",id=\"/\",instance=~\"$node\"}) / on (instance) label_join(kube_node_status_allocatable_memory_bytes{cluster=\"$cluster\"},\"instance\",\"\",\"node\")",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (container_memory_working_set_bytes{cluster=\"$cluster\",id=\"/\",instance=~\"$node\"}) / on (instance) label_join(kube_node_status_allocatable_memory_bytes{cluster=\"$cluster\"},\"instance\",\"\",\"node\")",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Filesystem",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_fs_limit_bytes{cluster=\"$cluster\",instance=~\"$node\",id=\"/\",device=~\"/dev/mapper/docker_data|/dev/nvme0n1p1|/dev/sda1\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(container_fs_usage_bytes{cluster=\"$cluster\",instance=~\"$node\",id=\"/\",device=~\"/dev/mapper/docker_data|/dev/nvme0n1p1|/dev/sda1\"})",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Filesystem Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{cluster=\"$cluster\",instance=~\"$node\",id=\"/\",device=~\"/dev/mapper/docker_data|/dev/nvme0n1p1|/dev/sda1\"}) / sum(container_fs_limit_bytes{cluster=\"$cluster\",instance=~\"$node\",id=\"/\",device=~\"/dev/mapper/docker_data|/dev/nvme0n1p1|/dev/sda1\"})"
    }
   ]
  },
  {
   "title": "Filesystem Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (container_fs_usage_bytes{cluster=\"$cluster\",instance=~\"$node\",id=\"/\",device=~\"/dev/mapper/docker_data|/dev/nvme0n1p1|/dev/sda1\"}) / sum by (instance) (container_fs_limit_bytes)",
     "legendFormat": "{{ instance }} "
    }
   ]
  },
  {
   "title": "Filesystem Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 22 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (container_fs_usage_bytes{cluster=\"$cluster\",instance=~\"$node\",id=\"/\",device=~\"/dev/mapper/docker_data|/dev/nvme0n1p1|/dev/sda1\"}) / sum by (instance) (container_fs_limit_bytes)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Filesystem Reads/Writes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{cluster=\"$cluster\",id=\"/\",device=~\"/dev/mapper/docker_data|/dev/nvme0n1|/dev/sda\"}[1m]))",
     "legendFormat": "Reads"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{cluster=\"$cluster\",id=\"/\",device=~\"/dev/mapper/docker_data|/dev/nvme0n1|/dev/sda\"}[1m]))",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Filesystem Reads/Writes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 30 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(container_fs_reads_bytes_total{cluster=\"$cluster\",instance=~\"$node\",id=\"/\",device=~\"/dev/mapper/docker_data|/dev/nvme0n1|/dev/sda\"}[1m]))",
     "legendFormat": "Reads : {{ instance }}"
    },
    {
     "expr": "sum by (instance) (rate(container_fs_writes_bytes_total{cluster=\"$cluster\",instance=~\"$node\",id=\"/\",device=~\"/dev/mapper/docker_data|/dev/nvme0n1|/dev/sda\"}[1m]))",
     "legendFormat": "Writes : {{ instance }}"
    }
   ]
  },
  {
   "title": "Network RX/TX",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum by (instance) (rate(container_network_receive_bytes_total{cluster=\"$cluster\",id=\"/\",instance=~\"$node\"}[1m])))",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum(sum by (instance) (rate(container_network_transmit_bytes_total{cluster=\"$cluster\",id=\"/\",instance=~\"$node\"}[1m])))",
     "legendFormat": "Transmit"
    }
   ]
  },
  {
   "title": "Network TX/RX",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 30 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(container_network_receive_bytes_total{cluster=\"$cluster\",id=\"/\",instance=~\"$node\"}[1m]))",
     "legendFormat": "RX : {{ instance }}"
    },
    {
     "expr": "sum by (instance) (rate(container_network_transmit_bytes_total{cluster=\"$cluster\",id=\"/\",instance=~\"$node\"}[1m]))",
     "legendFormat": "TX : {{ instance }}"
    }
   ]
  },
  {
   "title": "Pod Allocation",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_running_pod_count{cluster=\"$cluster\",instance=~\"$node\"} / on (instance) label_join(kube_node_status_allocatable_pods{cluster=\"$cluster\"},\"instance\",\"\",\"node\")",
     "legendFormat": "{{ instance }} "
    }
   ]
  },
  {
   "title": "Running Pod Count",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (kubelet_running_pod_count{cluster=\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Running Pod Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (kubelet_running_pod_count{cluster=\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Running Container Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (kubelet_running_container_count{cluster=\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (priority) (ALERTS{cluster=\"$cluster\",alertstate=\"firing\"})",
     "legendFormat": "{{ priority }}"
    }
   ]
  }
 ]
}