{
 "title": "Kubernetes: Clusters Overview",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(kube_node_labels, cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "Provider",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(count by (cluster) (kube_node_info{cluster!=\"\",provider_id=~\"aws:.*\"}))",
     "legendFormat": "AWS"
    },
    {
     "expr": "count(count by (cluster) (kube_node_info{cluster!=\"\",provider_id=~\"azure:.*\"}))",
     "legendFormat": "Azure"
    },
    {
     "expr": "count(count by (cluster) (kube_node_info{cluster!=\"\",provider_id=~\"ibm:.*\"}))",
     "legendFormat": "IBM"
    }
   ]
  },
  {
   "title": "Number of",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(count by (cluster) (kube_node_info))",
     "legendFormat": "Clusters"
    },
    { "expr": "count(kube_node_info)", "legendFormat": "Nodes" },
    { "expr": "count(kube_namespace_created)", "legendFormat": "Namespaces" }
   ]
  },
  {
   "title": "Running",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kubelet_running_pod_count)", "legendFormat": "Pod" },
    {
     "expr": "sum(kubelet_running_container_count)",
     "legendFormat": "Container"
    }
   ]
  },
  {
   "title": "Unschedulable",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable)"
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status!=\"true\"})",
     "legendFormat": "Not Ready"
    },
    {
     "expr": "sum(kube_node_status_condition{condition=\"MemoryPressure\",status=\"true\"})",
     "legendFormat": "Memory Pressure"
    },
    {
     "expr": "sum(kube_node_status_condition{condition=\"DiskPressure\",status=\"true\"})",
     "legendFormat": "Disk Pressure"
    },
    {
     "expr": "sum(kube_node_status_condition{condition=\"PIDPressure\",status=\"true\"})",
     "legendFormat": "PID Pressure"
    }
   ]
  },
  {
   "title": "Alerts Firing(P1)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\",alertname!=\"DeadMansSwitch\",priority=\"P1\"}) or (1-absent(ALERTS{alertstate=\"firing\",alertname!=\"DeadMansSwitch\",priority=\"P1\"}))",
     "legendFormat": "P1"
    }
   ]
  },
  {
   "title": "Alerts Firing(P2~P5)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\",alertname!=\"DeadMansSwitch\",priority=\"P2\"}) or (1-absent(ALERTS{alertstate=\"firing\",alertname!=\"DeadMansSwitch\",priority=\"P2\"}))",
     "legendFormat": "P2"
    },
    {
     "expr": "sum(ALERTS{alertstate=\"firing\",alertname!=\"DeadMansSwitch\",priority=\"P3\"}) or (1-absent(ALERTS{alertstate=\"firing\",alertname!=\"DeadMansSwitch\",priority=\"P3\"}))",
     "legendFormat": "P3"
    },
    {
     "expr": "sum(ALERTS{alertstate=\"firing\",alertname!=\"DeadMansSwitch\",priority=\"P4\"}) or (1-absent(ALERTS{alertstate=\"firing\",alertname!=\"DeadMansSwitch\",priority=\"P4\"}))",
     "legendFormat": "P4"
    },
    {
     "expr": "sum(ALERTS{alertstate=\"firing\",alertname!=\"DeadMansSwitch\",priority=\"P5\"}) or (1-absent(ALERTS{alertstate=\"firing\",alertname!=\"DeadMansSwitch\",priority=\"P5\"}))",
     "legendFormat": "P5"
    }
   ]
  },
  {
   "title": "Resource Usage($cluster)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 6 },
   "repeat": "cluster",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",id=\"/\"}[1m])) / sum(kube_node_status_allocatable_cpu_cores{cluster=\"$cluster\"})",
     "legendFormat": "CPU"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\",id=\"/\"}) / sum(kube_node_status_allocatable_memory_bytes{cluster=\"$cluster\"})",
     "legendFormat": "Memory"
    },
    {
     "expr": "sum(container_fs_usage_bytes{cluster=\"$cluster\",id=\"/\",device=~\"/dev/mapper/docker_data|/dev/nvme0n1p1|/dev/sda1\"}) / sum(container_fs_limit_bytes{cluster=\"$cluster\",id=\"/\",device=~\"/dev/mapper/docker_data|/dev/nvme0n1p1|/dev/sda1\"})",
     "legendFormat": "Filesystem"
    }
   ]
  },
  {
   "title": "CPU Usage($cluster)",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 7, "x": 3, "y": 6 },
   "repeat": "cluster",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",id=\"/\"}[1m])) / on (instance) label_join(kube_node_status_allocatable_cpu_cores{cluster=\"$cluster\"},\"instance\",\"\",\"node\")",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory Usage($cluster)",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 7, "x": 10, "y": 6 },
   "repeat": "cluster",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (container_memory_working_set_bytes{cluster=\"$cluster\",id=\"/\"}) / on (instance) label_join(kube_node_status_allocatable_memory_bytes{cluster=\"$cluster\"},\"instance\",\"\",\"node\")",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Filesystem Usage($cluster)",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 6 },
   "repeat": "cluster",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (container_fs_usage_bytes{cluster=\"$cluster\",id=\"/\",device=~\"/dev/mapper/docker_data|/dev/nvme0n1p1|/dev/sda1\"}) / sum by (instance) (container_fs_limit_bytes)",
     "legendFormat": "{{ instance }} "
    }
   ]
  },
  {
   "title": "Resource Usage($cluster)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",id=\"/\"}[1m])) / sum(kube_node_status_allocatable_cpu_cores{cluster=\"$cluster\"})",
     "legendFormat": "CPU"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\",id=\"/\"}) / sum(kube_node_status_allocatable_memory_bytes{cluster=\"$cluster\"})",
     "legendFormat": "Memory"
    },
    {
     "expr": "sum(container_fs_usage_bytes{cluster=\"$cluster\",id=\"/\",device=~\"/dev/mapper/docker_data|/dev/nvme0n1p1|/dev/sda1\"}) / sum(container_fs_limit_bytes{cluster=\"$cluster\",id=\"/\",device=~\"/dev/mapper/docker_data|/dev/nvme0n1p1|/dev/sda1\"})",
     "legendFormat": "Filesystem"
    }
   ]
  },
  {
   "title": "CPU Usage($cluster)",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 7, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",id=\"/\"}[1m])) / on (instance) label_join(kube_node_status_allocatable_cpu_cores{cluster=\"$cluster\"},\"instance\",\"\",\"node\")",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory Usage($cluster)",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 7, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (container_memory_working_set_bytes{cluster=\"$cluster\",id=\"/\"}) / on (instance) label_join(kube_node_status_allocatable_memory_bytes{cluster=\"$cluster\"},\"instance\",\"\",\"node\")",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Filesystem Usage($cluster)",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (container_fs_usage_bytes{cluster=\"$cluster\",id=\"/\",device=~\"/dev/mapper/docker_data|/dev/nvme0n1p1|/dev/sda1\"}) / sum by (instance) (container_fs_limit_bytes)",
     "legendFormat": "{{ instance }} "
    }
   ]
  },
  {
   "title": "Resource Usage($cluster)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",id=\"/\"}[1m])) / sum(kube_node_status_allocatable_cpu_cores{cluster=\"$cluster\"})",
     "legendFormat": "CPU"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\",id=\"/\"}) / sum(kube_node_status_allocatable_memory_bytes{cluster=\"$cluster\"})",
     "legendFormat": "Memory"
    },
    {
     "expr": "sum(container_fs_usage_bytes{cluster=\"$cluster\",id=\"/\",device=~\"/dev/mapper/docker_data|/dev/nvme0n1p1|/dev/sda1\"}) / sum(container_fs_limit_bytes{cluster=\"$cluster\",id=\"/\",device=~\"/dev/mapper/docker_data|/dev/nvme0n1p1|/dev/sda1\"})",
     "legendFormat": "Filesystem"
    }
   ]
  },
  {
   "title": "CPU Usage($cluster)",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 7, "x": 3, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",id=\"/\"}[1m])) / on (instance) label_join(kube_node_status_allocatable_cpu_cores{cluster=\"$cluster\"},\"instance\",\"\",\"node\")",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory Usage($cluster)",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 7, "x": 10, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (container_memory_working_set_bytes{cluster=\"$cluster\",id=\"/\"}) / on (instance) label_join(kube_node_status_allocatable_memory_bytes{cluster=\"$cluster\"},\"instance\",\"\",\"node\")",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Filesystem Usage($cluster)",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (container_fs_usage_bytes{cluster=\"$cluster\",id=\"/\",device=~\"/dev/mapper/docker_data|/dev/nvme0n1p1|/dev/sda1\"}) / sum by (instance) (container_fs_limit_bytes)",
     "legendFormat": "{{ instance }} "
    }
   ]
  },
  {
   "title": "Resource Usage($cluster)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",id=\"/\"}[1m])) / sum(kube_node_status_allocatable_cpu_cores{cluster=\"$cluster\"})",
     "legendFormat": "CPU"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\",id=\"/\"}) / sum(kube_node_status_allocatable_memory_bytes{cluster=\"$cluster\"})",
     "legendFormat": "Memory"
    },
    {
     "expr": "sum(container_fs_usage_bytes{cluster=\"$cluster\",id=\"/\",device=~\"/dev/mapper/docker_data|/dev/nvme0n1p1|/dev/sda1\"}) / sum(container_fs_limit_bytes{cluster=\"$cluster\",id=\"/\",device=~\"/dev/mapper/docker_data|/dev/nvme0n1p1|/dev/sda1\"})",
     "legendFormat": "Filesystem"
    }
   ]
  },
  {
   "title": "CPU Usage($cluster)",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 7, "x": 3, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",id=\"/\"}[1m])) / on (instance) label_join(kube_node_status_allocatable_cpu_cores{cluster=\"$cluster\"},\"instance\",\"\",\"node\")",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory Usage($cluster)",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 7, "x": 10, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (container_memory_working_set_bytes{cluster=\"$cluster\",id=\"/\"}) / on (instance) label_join(kube_node_status_allocatable_memory_bytes{cluster=\"$cluster\"},\"instance\",\"\",\"node\")",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Filesystem Usage($cluster)",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (container_fs_usage_bytes{cluster=\"$cluster\",id=\"/\",device=~\"/dev/mapper/docker_data|/dev/nvme0n1p1|/dev/sda1\"}) / sum by (instance) (container_fs_limit_bytes)",
     "legendFormat": "{{ instance }} "
    }
   ]
  }
 ]
}