apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zcp-system
commonLabels:
  release: zcp-monitoring
bases:
- ./alertmanager
- ./grafana
- ./prometheus
resources:
- exporters/blackbox-exporter/blackbox-exporter-config-cm.yaml
- exporters/blackbox-exporter/blackbox-exporter-deployment.yaml
- exporters/blackbox-exporter/blackbox-exporter-service.yaml
- exporters/kube-state-metric/kube-state-metrics-deployment.yaml
- exporters/kube-state-metric/kube-state-metrics-rbac.yaml
- exporters/kube-state-metric/kube-state-metrics-svc.yaml
- exporters/node-exporter/node-exporter-ds-svc.yaml
- exporters/node-exporter/node-exporter-ds.yaml
generatorOptions:
  disableNameSuffixHash: true