{
 "title": "System: Overview",
 "tags": [ "System" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(node_load1, cluster)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(node_load1{cluster=\"$cluster\",job=\"kubernetes-nodes-exporter\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu{cluster=\"$cluster\",instance=~\"$node\",mode=\"user\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(1 - irate(node_cpu{cluster=\"$cluster\",instance=~\"$node\",mode=\"idle\"}[1m]))",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "$node CPU Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(1 - irate(node_cpu{cluster=\"$cluster\",instance=~\"$node\",job=\"kubernetes-nodes-exporter\",mode=\"idle\"}[1m])) / count(node_cpu{cluster=\"$cluster\",instance=~\"$node\",mode=\"user\",job=\"kubernetes-nodes-exporter\"})"
    }
   ]
  },
  {
   "title": "$node CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (avg by (instance) (rate(node_cpu{cluster=\"$cluster\",instance=~\"$node\",mode=\"idle\"}[1m])))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "$node CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (avg by (instance) (rate(node_cpu{cluster=\"$cluster\",job=\"kubernetes-nodes-exporter\",mode=\"idle\"}[1m])))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal{cluster=\"$cluster\",instance=~\"$node\",job=\"kubernetes-nodes-exporter\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(node_memory_MemTotal{cluster=\"$cluster\",instance=~\"$node\",job=\"kubernetes-nodes-exporter\"} - node_memory_MemFree - node_memory_Buffers - node_memory_Cached )",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(node_memory_MemTotal{cluster=\"$cluster\",instance=~\"$node\",job=\"kubernetes-nodes-exporter\"} - node_memory_MemAvailable )",
     "legendFormat": "Unavailable"
    }
   ]
  },
  {
   "title": "$node Memory Used",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal{cluster=\"$cluster\",instance=~\"$node\"} - node_memory_MemFree - node_memory_Buffers - node_memory_Cached ) / sum(node_memory_MemTotal{cluster=\"$cluster\",instance=~\"$node\"})"
    }
   ]
  },
  {
   "title": "$node Memory Used",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) ((node_memory_MemTotal - node_memory_MemFree - node_memory_Buffers - node_memory_Cached) / node_memory_MemTotal{cluster=\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "$node Memory Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) ((node_memory_MemTotal - node_memory_MemFree - node_memory_Buffers - node_memory_Cached) / node_memory_MemTotal{cluster=\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Filesystem",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size{cluster=\"$cluster\",job=\"kubernetes-nodes-exporter\",mountpoint=\"/\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(node_filesystem_size{cluster=\"$cluster\",job=\"kubernetes-nodes-exporter\",mountpoint=\"/\"}) - sum(node_filesystem_free{cluster=\"$cluster\",job=\"kubernetes-nodes-exporter\",mountpoint=\"/\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(node_filesystem_size{cluster=\"$cluster\",job=\"kubernetes-nodes-exporter\",mountpoint=\"/\"}) - sum(node_filesystem_avail{cluster=\"$cluster\",job=\"kubernetes-nodes-exporter\",mountpoint=\"/\"})",
     "legendFormat": "Unavailable"
    }
   ]
  },
  {
   "title": "$node Filesystem Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_filesystem_size{cluster=\"$cluster\",job=\"kubernetes-nodes-exporter\",mountpoint=\"/\"}) - sum(node_filesystem_avail{cluster=\"$cluster\",job=\"kubernetes-nodes-exporter\",mountpoint=\"/\"})) / sum(node_filesystem_size{cluster=\"$cluster\",job=\"kubernetes-nodes-exporter\",mountpoint=\"/\"})"
    }
   ]
  },
  {
   "title": "$node Filesystem Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) ((node_filesystem_size - node_filesystem_avail) / node_filesystem_size{cluster=\"$cluster\",instance=~\"$node\",mountpoint=\"/\"})",
     "legendFormat": "{{ instance }} "
    }
   ]
  },
  {
   "title": "$node Filesystem Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) ((node_filesystem_size - node_filesystem_avail) / node_filesystem_size{cluster=\"$cluster\",instance=~\"$node\",mountpoint=\"/\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Number of Node",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(node_uname_info{cluster=\"$cluster\",job=\"kubernetes-nodes-exporter\"})"
    }
   ]
  },
  {
   "title": "Avg CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 3, "y": 24 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(100 - (avg by (cpu) (rate(node_cpu{job=\"kubernetes-nodes-exporter\",mode=\"idle\"}[5m])) * 100))"
    }
   ]
  },
  {
   "title": "Disk Usage(Local)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((node_filesystem_size{cluster=\"$cluster\",job=\"kubernetes-nodes-exporter\",mountpoint=\"/\"} - node_filesystem_avail{job=\"kubernetes-nodes-exporter\",mountpoint=\"/\"}) / node_filesystem_size{job=\"kubernetes-nodes-exporter\",mountpoint=\"/\"}) * 100",
     "legendFormat": "{{ instance }} {{ device }}"
    }
   ]
  },
  {
   "title": "Avg Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 3, "y": 31 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal{job=\"kubernetes-nodes-exporter\"} - node_memory_MemFree - node_memory_Buffers - node_memory_Cached ) / sum(node_memory_MemTotal{job=\"kubernetes-nodes-exporter\"}) * 100"
    }
   ]
  },
  {
   "title": "Network Usage(RX/TX)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 31 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(sum by (instance) (rate(node_network_receive_bytes{cluster=\"$cluster\",job=\"kubernetes-nodes-exporter\",device=~\"eth0|eth1\"}[1m])))",
     "legendFormat": "Inbound: {{ instance }} "
    },
    {
     "expr": "(sum by (instance) (rate(node_network_transmit_bytes{cluster=\"$cluster\",job=\"kubernetes-nodes-exporter\",device=~\"eth0|eth1\"}[1m])))",
     "legendFormat": "Outbound: {{ instance }}"
    }
   ]
  },
  {
   "title": "Avg Disk Usage(Local)",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 3, "y": 38 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "((sum(node_filesystem_size{job=\"kubernetes-nodes-exporter\",mountpoint=\"/\"}) - sum(node_filesystem_avail{job=\"kubernetes-nodes-exporter\",mountpoint=\"/\"})) / sum(node_filesystem_size{job=\"kubernetes-nodes-exporter\",mountpoint=\"/\"})) * 100"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_MemTotal{instance=\"$host\"}",
     "legendFormat": "Total"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_MemTotal{instance=\"$host\"} - (node_memory_MemAvailable{instance=\"$host\"} or (node_memory_MemFree{instance=\"$host\"} + node_memory_Buffers{instance=\"$host\"} + node_memory_Cached{instance=\"$host\"}))",
     "legendFormat": "Used"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_MemAvailable{instance=\"$host\"} or (node_memory_MemFree{instance=\"$host\"} + node_memory_Buffers{instance=\"$host\"} + node_memory_Cached{instance=\"$host\"})",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Memory Distribution",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_MemTotal{instance=\"$host\"} - (node_memory_MemFree{instance=\"$host\"} + node_memory_Buffers{instance=\"$host\"} + node_memory_Cached{instance=\"$host\"})",
     "legendFormat": "Used"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_MemFree{instance=\"$host\"}",
     "legendFormat": "Free"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_Buffers{instance=\"$host\"}",
     "legendFormat": "Buffers"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_Cached{instance=\"$host\"}",
     "legendFormat": "Cached"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "10s",
     "expr": "node_load1{instance=\"$host\"}",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{instance=\"$host\"}",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{instance=\"$host\"}",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "Network Utilization Hourly",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "sum(increase(node_network_receive_bytes{instance=\"$host\", device!=\"lo\"}[1h]))",
     "legendFormat": "Received"
    },
    {
     "calculatedInterval": "2s",
     "expr": "sum(increase(node_network_transmit_bytes{instance=\"$host\", device!=\"lo\"}[1h]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "sum(rate(node_cpu{instance=\"$host\"}[$interval])) by (mode) * 100 / scalar(count(node_cpu{mode=\"user\", instance=\"$host\"})) or sum(irate(node_cpu{instance=\"$host\"}[5m])) by (mode) * 100 / scalar(count(node_cpu{mode=\"user\", instance=\"$host\"}))",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "sum by (instance) (rate(node_disk_bytes_read{instance=\"$host\"}[2m]))",
     "legendFormat": "read"
    },
    {
     "calculatedInterval": "2s",
     "expr": "sum by (instance) (rate(node_disk_bytes_written{instance=\"$host\"}[2m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum by (instance) (rate(node_disk_io_time_ms{instance=\"$host\"}[2m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_network_receive_bytes{instance=\"$host\", device!=\"lo\"}[$interval]) or irate(node_network_receive_bytes{instance=\"$host\", device!=\"lo\"}[5m])",
     "legendFormat": "Inbound: {{ device }}"
    },
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_network_transmit_bytes{instance=\"$host\", device!=\"lo\"}[$interval]) or irate(node_network_transmit_bytes{instance=\"$host\", device!=\"lo\"}[5m])",
     "legendFormat": "Outbound: {{ device }}"
    }
   ]
  },
  {
   "title": "Swap Activity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_vmstat_pswpin{instance=\"$host\"}[$interval]) * 4096 or irate(node_vmstat_pswpin{instance=\"$host\"}[5m]) * 4096",
     "legendFormat": "Swap In"
    },
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_vmstat_pswpout{instance=\"$host\"}[$interval]) * 4096 or irate(node_vmstat_pswpout{instance=\"$host\"}[5m]) * 4096",
     "legendFormat": "Swap Out"
    }
   ]
  },
  {
   "title": "Filsystem Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "node_filesystem_size{instance=~\"$host\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\",mountpoint=\"/\"}",
     "legendFormat": "Total (device {{ device }}, {{ fstype }})"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_filesystem_size{instance=~\"$host\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\",mountpoint=\"/\"} - node_filesystem_avail{instance=~\"$host\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\",mountpoint=\"/\"}",
     "legendFormat": "Used (device {{ device }}, {{ fstype }})"
    },
    {
     "expr": "node_filesystem_avail{instance=~\"$host\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\",mountpoint=\"/\"}",
     "legendFormat": "Available (device {{ device }}, {{ fstype }})"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_SwapTotal{instance=\"$host\"} - node_memory_SwapFree{instance=\"$host\"}",
     "legendFormat": "Used"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_SwapFree{instance=\"$host\"}",
     "legendFormat": "Free"
    }
   ]
  }
 ]
}