{
 "title": "System: Node Overview",
 "tags": [ "system" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(node_load1, cluster)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(node_load1{cluster=\"$cluster\",job=\"kubernetes-nodes-exporter\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "System Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "node_time{cluster=\"$cluster\",instance=\"$host\"} - node_boot_time"
    }
   ]
  },
  {
   "title": "Virtual CPUs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu{cluter=\"$cluster\",instance=\"$host\",mode=\"user\"})"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal{cluster=\"$cluster\",instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "(node_memory_MemAvailable{cluster=\"$cluster\",instance=\"$host\"} or (node_memory_MemFree{instance=\"$host\"} + node_memory_Buffers{instance=\"$host\"} + node_memory_Cached{instance=\"$host\"})) / node_memory_MemTotal{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "10s",
     "expr": "node_load1{cluster=\"$cluster\",instance=\"$host\"}",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{cluster=\"$cluster\",instance=\"$host\"}",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{cluster=\"$cluster\",instance=\"$host\"}",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_MemTotal{cluster=\"$cluster\",instance=\"$host\"}",
     "legendFormat": "Total"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_MemTotal{cluster=\"$cluster\",instance=\"$host\"} - (node_memory_MemAvailable{instance=\"$host\"} or (node_memory_MemFree{cluster=\"$cluster\",instance=\"$host\"} + node_memory_Buffers{instance=\"$host\"} + node_memory_Cached{instance=\"$host\"}))",
     "legendFormat": "Used"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_MemAvailable{cluster=\"$cluster\",instance=\"$host\"} or (node_memory_MemFree{cluster=\"$cluster\",instance=\"$host\"} + node_memory_Buffers{instance=\"$host\"} + node_memory_Cached{instance=\"$host\"})",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "sum(rate(node_cpu{cluster=\"$cluster\",instance=\"$host\"}[1m])) by (mode) * 100 / scalar(count(node_cpu{mode=\"user\", instance=\"$host\"})) or sum(irate(node_cpu{cluster=\"$cluster\",instance=\"$host\"}[1m])) by (mode) * 100 / scalar(count(node_cpu{mode=\"user\", instance=\"$host\"}))",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Memory Distribution",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_MemTotal{cluster=\"$cluster\",instance=\"$host\"} - (node_memory_MemFree{instance=\"$host\"} + node_memory_Buffers{instance=\"$host\"} + node_memory_Cached{instance=\"$host\"})",
     "legendFormat": "Used"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_MemFree{instance=\"$host\"}",
     "legendFormat": "Free"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_Buffers{instance=\"$host\"}",
     "legendFormat": "Buffers"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_Cached{instance=\"$host\"}",
     "legendFormat": "Cached"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_network_receive_bytes{cluster=\"$cluster\",instance=\"$host\", device!=\"lo\"}[1m]) or irate(node_network_receive_bytes{instance=\"$host\", device!=\"lo\"}[1m])",
     "legendFormat": "Inbound: {{ device }}"
    },
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_network_transmit_bytes{cluster=\"$cluster\",instance=\"$host\", device!=\"lo\"}[1m]) or irate(node_network_transmit_bytes{instance=\"$host\", device!=\"lo\"}[5m])",
     "legendFormat": "Outbound: {{ device }}"
    }
   ]
  },
  {
   "title": "Network Utilization Hourly",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "sum(increase(node_network_receive_bytes{cluster=\"$cluster\",instance=\"$host\", device!=\"lo\"}[1h]))",
     "legendFormat": "Received"
    },
    {
     "calculatedInterval": "2s",
     "expr": "sum(increase(node_network_transmit_bytes{cluster=\"$cluster\",instance=\"$host\", device!=\"lo\"}[1h]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Filsystem Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "node_filesystem_size{cluster=\"$cluster\",instance=~\"$host\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\",mountpoint=\"/\"}",
     "legendFormat": "Total (device {{ device }}, {{ fstype }})"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_filesystem_size{cluster=\"$cluster\",instance=~\"$host\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\",mountpoint=\"/\"} - node_filesystem_avail{cluster=\"$cluster\",instance=~\"$host\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\",mountpoint=\"/\"}",
     "legendFormat": "Used (device {{ device }}, {{ fstype }})"
    },
    {
     "expr": "node_filesystem_avail{cluster=\"$cluster\",instance=~\"$host\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\",mountpoint=\"/\"}",
     "legendFormat": "Available (device {{ device }}, {{ fstype }})"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "sum by (instance) (rate(node_disk_bytes_read{cluster=\"$cluster\",instance=\"$host\"}[2m]))",
     "legendFormat": "read"
    },
    {
     "calculatedInterval": "2s",
     "expr": "sum by (instance) (rate(node_disk_bytes_written{cluster=\"$cluster\",instance=\"$host\"}[2m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum by (instance) (rate(node_disk_io_time_ms{cluster=\"$cluster\",instance=\"$host\"}[2m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Mountpoint $mountpoint",
   "type": "graph",
   "description": "Amount of disk space used and available on various mount points.  Running out of disk space on OS volume,  database volume or volume used for temporary space can cause downtime.   Some storage may also have reduced performance when small amount of space is available.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "repeat": "mountpoint",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "node_filesystem_size{cluster=\"$cluster\",instance=~\"$host\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"} - node_filesystem_avail{instance=~\"$host\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}",
     "legendFormat": "Used (device {{ device }}, {{ fstype }})"
    },
    {
     "calculatedInterval": "2m",
     "expr": "node_filesystem_avail{cluster=\"$cluster\",instance=~\"$host\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\", mountpoint=\"$mountpoint\"}",
     "legendFormat": "Free (device {{ device }}, {{ fstype }})"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_SwapTotal{cluster=\"$cluster\",instance=\"$host\"} - node_memory_SwapFree{instance=\"$host\"}",
     "legendFormat": "Used"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_SwapFree{cluster=\"$cluster\",instance=\"$host\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Swap Activity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_vmstat_pswpin{cluster=\"$cluster\",instance=\"$host\"}[1m]) * 4096 or irate(node_vmstat_pswpin{instance=\"$host\"}[5m]) * 4096",
     "legendFormat": "Swap In"
    },
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_vmstat_pswpout{cluster=\"$cluster\",instance=\"$host\"}[1m]) * 4096 or irate(node_vmstat_pswpout{instance=\"$host\"}[5m]) * 4096",
     "legendFormat": "Swap Out"
    }
   ]
  }
 ]
}