{
 "title": "Kubernetes: DaemonSet Overview",
 "description": "Kubernetes: DaemonSet Overview",
 "tags": [
  "kubernetes",
  "daemonset"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "daemonset_namespace",
    "label": "Namespace",
    "query": "label_values(kube_daemonset_metadata_generation, namespace)"
   },
   {
    "name": "daemonset_name",
    "label": "DaemonSet",
    "query": "label_values(kube_daemonset_metadata_generation{namespace=\"$daemonset_namespace\"}, daemonset)"
   },
   {
    "name": "pod_name",
    "label": "Pod",
    "query": "label_values(kube_pod_info{namespace=\"$daemonset_namespace\",created_by_kind=\"DaemonSet\",created_by_name=\"$daemonset_name\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "DESIRED",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_daemonset_status_desired_number_scheduled{daemonset=\"$daemonset_name\",namespace=\"$daemonset_namespace\"}"
    }
   ]
  },
  {
   "title": "CURRENT",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_daemonset_status_current_number_scheduled{daemonset=\"$daemonset_name\",namespace=\"$daemonset_namespace\"}"
    }
   ]
  },
  {
   "title": "READY",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_daemonset_status_number_ready{daemonset=\"$daemonset_name\",namespace=\"$daemonset_namespace\"}"
    }
   ]
  },
  {
   "title": "AVAILABLE",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_daemonset_status_number_available{daemonset=\"$daemonset_name\",namespace=\"$daemonset_namespace\"}"
    }
   ]
  },
  {
   "title": "Metadata Generation",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_daemonset_metadata_generation{daemonset=\"$daemonset_name\",namespace=\"$daemonset_namespace\"}"
    }
   ]
  },
  {
   "title": "DaemonSet Create Time",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 3 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - kube_daemonset_created{daemonset=~\"$daemonset_name\"}"
    }
   ]
  },
  {
   "title": "Total CPU",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 7, "x": 3, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$daemonset_namespace\",pod_name=~\"$pod_name\",container_name!=\"POD\",container_name!=\"\"}[2m]))"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$daemonset_namespace\",pod_name=~\"$pod_name\",container_name!=\"POD\",container_name!=\"\"})"
    }
   ]
  },
  {
   "title": "Total Network",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 3 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$daemonset_namespace\",pod_name=~\"$pod_name\"}[2m])) + sum(rate(container_network_receive_bytes_total{namespace=\"$daemonset_namespace\",pod_name=~\"$pod_name\"}[2m]))"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (rate(container_cpu_usage_seconds_total{namespace=\"$daemonset_namespace\",pod_name=~\"$pod_name\",container_name!=\"POD\",container_name!=\"\"}[2m]))",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (container_memory_working_set_bytes{namespace=\"$daemonset_namespace\",pod_name=~\"$pod_name\",container_name!=\"POD\",container_name!=\"\"})",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Filesystem Read/Write",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (rate(container_fs_reads_bytes_total{namespace=\"$daemonset_namespace\",pod_name=~\"$pod_name\",container_name!=\"POD\",container_name!=\"\"}[2m]))",
     "legendFormat": "Reads: {{ pod_name }}"
    },
    {
     "expr": "sum by (pod_name) (rate(container_fs_writes_bytes_total{namespace=\"$daemonset_namespace\",pod_name=~\"$pod_name\",container_name!=\"POD\",container_name!=\"\"}[2m]))",
     "legendFormat": "Writes: {{ pod_name }}"
    }
   ]
  },
  {
   "title": "Network TX/RX",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (rate(container_network_transmit_bytes_total{namespace=\"$daemonset_namespace\",pod_name=~\"$pod_name\"}[2m]))",
     "legendFormat": "TX: {{ pod_name }}"
    },
    {
     "expr": "sum by (pod_name)(rate(container_network_receive_bytes_total{namespace=\"$daemonset_namespace\",pod_name=~\"$pod_name\"}[2m]))",
     "legendFormat": "RX: {{ pod_name }}"
    }
   ]
  },
  {
   "title": "Replicas Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg(kube_daemonset_status_number_ready{daemonset=\"$daemonset_name\",namespace=\"$daemonset_namespace\"}) without (instance, pod)",
     "legendFormat": "Ready"
    },
    {
     "expr": "avg(kube_daemonset_status_number_available{daemonset=\"$daemonset_name\",namespace=\"$daemonset_namespace\"}) without (instance, pod)",
     "legendFormat": "Available"
    },
    {
     "expr": "avg(kube_daemonset_status_number_unavailable{daemonset=\"$daemonset_name\",namespace=\"$daemonset_namespace\"}) without (instance, pod)",
     "legendFormat": "Unavailable"
    },
    {
     "expr": "avg(kube_daemonset_status_number_misscheduled{daemonset=\"$daemonset_name\",namespace=\"$daemonset_namespace\"}) without (instance, pod)",
     "legendFormat": "Misscheduled"
    }
   ]
  }
 ]
}