apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: monitoring-prometheus-ingress
  namespace: zcp-system
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"